export type EventPhase = 'agrumeto' | 'rito' | 'sala_tufo' | 'torta' | 'after_party' | 'generale';

export interface ServiceCatalogItem {
  id: string;
  code: string;
  categoria: string;
  nome: string;
  titoloBase?: string;
  variante?: string;
  descrizione: string;
  prezzo_unitario: number;
  costo_fornitore?: number;
  fase_evento?: EventPhase;
  unita_misura: 'pax' | 'corpo' | 'child';
  unitaLabel: string;
  splitLabel: string;
  splitKey: string;
  immagine: string;
  galleria?: string[];
  created_at?: string;
  updated_at?: string;
}

export interface ServiceSplitResult {
  // Legacy / Verbose naming (used in CatalogoClient.tsx)
  santoStefanoNet: number;  // Imponibile Santo Stefano Srl (IVA 22%)
  iovinoNet: number;        // Imponibile Iovino Banquetting (IVA 10%)
  santoStefanoIva: number;  // 22% IVA
  iovinoIva: number;        // 10% IVA
  santoStefanoTotal: number;// Totale Santo Stefano con IVA
  iovinoTotal: number;      // Totale Iovino con IVA

  // Short & Standard naming (used across simulator & new modules)
  ssNet: number;
  iovNet: number;
  ssIva: number;
  iovIva: number;
  ssTot: number;
  iovTot: number;
  totalNet: number;
  totalIva: number;
  totalGross: number;
  ssSplitPercent: number;
  iovSplitPercent: number;
}

export interface VillaMarginResult {
  prezzoVendita: number;
  costoFornitore: number;
  margineNetto: number;
  marginePercentuale: number;
  isEsterno: boolean;
}

/**
 * Calcola la suddivisione esatta tra Santo Stefano Srl (22% IVA) ed Iovino Banquetting (10% IVA)
 * per qualsiasi servizio o importo custom.
 */
export function calculateServiceSplit(price: number, splitKey: string = "", splitLabel: string = ""): ServiceSplitResult {
  const key = (splitKey || "").toLowerCase();
  const label = (splitLabel || "").toLowerCase();

  let ssNet = 0;
  let iovNet = 0;

  if (key === "40_60" || key === "ric_40_60" || label.includes("40%") || label.includes("60%")) {
    ssNet = price * 0.40;
    iovNet = price * 0.60;
  } else if (key === "ss100" || label.includes("100% santo stefano")) {
    ssNet = price;
    iovNet = 0;
  } else if (key === "i100" || label.includes("100% iovino")) {
    ssNet = 0;
    iovNet = price;
  } else if (key === "ss100fixed" || key === "angle" || key === "angoli" || label.includes("100 santo stefano") || label.includes("angle")) {
    ssNet = Math.min(price, 100);
    iovNet = Math.max(0, price - 100);
  } else if (key === "ss50" || label.includes("50 santo stefano")) {
    ssNet = Math.min(price, 50);
    iovNet = Math.max(0, price - 50);
  } else if (key === "ss25" || key === "ss25cap" || label.includes("25 santo stefano")) {
    ssNet = Math.min(price, 25);
    iovNet = Math.max(0, price - 25);
  } else if (key === "after" || key === "after_party") {
    // After Party: SS 40% su €1.750 (€700); Iovino 60% su €1.750 (€1.050) + eccedenza
    const base = Math.min(price, 1750);
    ssNet = base * 0.40;
    iovNet = (base * 0.60) + Math.max(0, price - 1750);
  } else {
    // Fallback: 40% Santo Stefano / 60% Iovino
    ssNet = price * 0.40;
    iovNet = price * 0.60;
  }

  const ssIva = Math.round(ssNet * 0.22 * 100) / 100;
  const iovIva = Math.round(iovNet * 0.10 * 100) / 100;
  const santoStefanoNet = Math.round(ssNet * 100) / 100;
  const iovinoNet = Math.round(iovNet * 100) / 100;
  const santoStefanoTotal = Math.round((santoStefanoNet + ssIva) * 100) / 100;
  const iovinoTotal = Math.round((iovinoNet + iovIva) * 100) / 100;

  const totalNet = Math.round((santoStefanoNet + iovinoNet) * 100) / 100;
  const totalIva = Math.round((ssIva + iovIva) * 100) / 100;
  const totalGross = Math.round((santoStefanoTotal + iovinoTotal) * 100) / 100;

  const ssSplitPercent = totalGross > 0 ? Math.round((santoStefanoTotal / totalGross) * 1000) / 10 : 40;
  const iovSplitPercent = totalGross > 0 ? Math.round((iovinoTotal / totalGross) * 1000) / 10 : 60;

  return {
    santoStefanoNet,
    iovinoNet,
    santoStefanoIva: ssIva,
    iovinoIva: iovIva,
    santoStefanoTotal,
    iovinoTotal,

    ssNet: santoStefanoNet,
    iovNet: iovinoNet,
    ssIva,
    iovIva,
    ssTot: santoStefanoTotal,
    iovTot: iovinoTotal,
    totalNet,
    totalIva,
    totalGross,
    ssSplitPercent,
    iovSplitPercent
  };
}

/**
 * Calcola il margine netto e la percentuale di ricarico per la Villa
 * rispetto al costo fornitore esterno.
 */
export function calculateVillaMargin(prezzo: number, costoFornitore?: number): VillaMarginResult {
  const p = typeof prezzo === 'number' && !isNaN(prezzo) ? prezzo : 0;
  const c = typeof costoFornitore === 'number' && !isNaN(costoFornitore) && costoFornitore > 0 ? costoFornitore : 0;
  const margineNetto = Math.round((p - c) * 100) / 100;
  const marginePercentuale = p > 0 ? Math.round(((p - c) / p) * 1000) / 10 : 0;
  const isEsterno = c > 0;

  return {
    prezzoVendita: p,
    costoFornitore: c,
    margineNetto,
    marginePercentuale,
    isEsterno
  };
}

export const SERVICES_CATALOG: ServiceCatalogItem[] = [
  {
    "id": "ric01",
    "code": "RIC01",
    "categoria": "Ricevimento",
    "nome": "Matrimonio adulti (70-99 adulti)",
    "titoloBase": "Matrimonio adulti",
    "variante": "70-99 adulti",
    "descrizione": "Servizio Ufficiale TDA: Matrimonio adulti (70-99 adulti) • Ripartizione: 40% Santo Stefano / 60% Iovino",
    "prezzo_unitario": 140,
    "unita_misura": "pax",
    "unitaLabel": "per adulto",
    "splitLabel": "40% Santo Stefano / 60% Iovino",
    "splitKey": "40_60",
    "immagine": "https://laterradegliaranci.it/wp-content/uploads/2024/07/sala-terradegliaranci.jpg",
    "costo_fornitore": 0,
    "fase_evento": "sala_tufo"
  },
  {
    "id": "ric02",
    "code": "RIC02",
    "categoria": "Ricevimento",
    "nome": "Matrimonio adulti (Da 100 adulti)",
    "titoloBase": "Matrimonio adulti",
    "variante": "Da 100 adulti",
    "descrizione": "Servizio Ufficiale TDA: Matrimonio adulti (Da 100 adulti) • Ripartizione: 40% Santo Stefano / 60% Iovino",
    "prezzo_unitario": 130,
    "unita_misura": "pax",
    "unitaLabel": "per adulto",
    "splitLabel": "40% Santo Stefano / 60% Iovino",
    "splitKey": "40_60",
    "immagine": "https://laterradegliaranci.it/wp-content/uploads/2024/07/sala-terradegliaranci.jpg",
    "costo_fornitore": 0,
    "fase_evento": "sala_tufo"
  },
  {
    "id": "ric03",
    "code": "RIC03",
    "categoria": "Ricevimento",
    "nome": "Menu bambini (Sempre)",
    "titoloBase": "Menu bambini",
    "variante": "Sempre",
    "descrizione": "Servizio Ufficiale TDA: Menu bambini (Sempre) • Ripartizione: 40% Santo Stefano / 60% Iovino",
    "prezzo_unitario": 50,
    "unita_misura": "child",
    "unitaLabel": "per bambino",
    "splitLabel": "40% Santo Stefano / 60% Iovino",
    "splitKey": "40_60",
    "immagine": "https://laterradegliaranci.it/wp-content/uploads/2024/07/sala-terradegliaranci.jpg",
    "costo_fornitore": 0,
    "fase_evento": "sala_tufo"
  },
  {
    "id": "ric04",
    "code": "RIC04",
    "categoria": "Ricevimento",
    "nome": "Menu Mandarancio (+ €10 per adulto)",
    "titoloBase": "Menu Mandarancio",
    "variante": "+ €10 per adulto",
    "descrizione": "Servizio Ufficiale TDA: Menu Mandarancio (+ €10 per adulto) • Ripartizione: 40% Santo Stefano / 60% Iovino",
    "prezzo_unitario": 10,
    "unita_misura": "pax",
    "unitaLabel": "per adulto",
    "splitLabel": "40% Santo Stefano / 60% Iovino",
    "splitKey": "40_60",
    "immagine": "https://laterradegliaranci.it/wp-content/uploads/2024/07/sala-terradegliaranci.jpg",
    "costo_fornitore": 0,
    "fase_evento": "sala_tufo"
  },
  {
    "id": "ric05",
    "code": "RIC05",
    "categoria": "Ricevimento",
    "nome": "Menu Arancio (+ €20 per adulto)",
    "titoloBase": "Menu Arancio",
    "variante": "+ €20 per adulto",
    "descrizione": "Servizio Ufficiale TDA: Menu Arancio (+ €20 per adulto) • Ripartizione: 40% Santo Stefano / 60% Iovino",
    "prezzo_unitario": 20,
    "unita_misura": "pax",
    "unitaLabel": "per adulto",
    "splitLabel": "40% Santo Stefano / 60% Iovino",
    "splitKey": "40_60",
    "immagine": "https://laterradegliaranci.it/wp-content/uploads/2024/07/sala-terradegliaranci.jpg",
    "costo_fornitore": 0,
    "fase_evento": "sala_tufo"
  },
  {
    "id": "ric06",
    "code": "RIC06",
    "categoria": "Ricevimento",
    "nome": "Supplemento sabato (Se ricevimento di sabato)",
    "titoloBase": "Supplemento sabato",
    "variante": "Se ricevimento di sabato",
    "descrizione": "Servizio Ufficiale TDA: Supplemento sabato (Se ricevimento di sabato) • Ripartizione: 40% Santo Stefano / 60% Iovino",
    "prezzo_unitario": 10,
    "unita_misura": "pax",
    "unitaLabel": "per adulto",
    "splitLabel": "40% Santo Stefano / 60% Iovino",
    "splitKey": "40_60",
    "immagine": "https://laterradegliaranci.it/wp-content/uploads/2024/07/sala-terradegliaranci.jpg",
    "costo_fornitore": 0,
    "fase_evento": "sala_tufo"
  },
  {
    "id": "ext01",
    "code": "EXT01",
    "categoria": "Extra ricevimento",
    "nome": "Animazione per bambini (Animatore base)",
    "titoloBase": "Animazione per bambini",
    "variante": "Animatore base",
    "descrizione": "Servizio Ufficiale TDA: Animazione per bambini (Animatore base) • Ripartizione: 100% Iovino",
    "prezzo_unitario": 100,
    "unita_misura": "corpo",
    "unitaLabel": "per animatore",
    "splitLabel": "100% Iovino",
    "splitKey": "i100",
    "immagine": "https://laterradegliaranci.it/wp-content/uploads/2024/07/sala-terradegliaranci.jpg",
    "costo_fornitore": 0,
    "fase_evento": "sala_tufo"
  },
  {
    "id": "ext02",
    "code": "EXT02",
    "categoria": "Extra ricevimento",
    "nome": "Pranzo/cena operatori interni (Prezzo menu bambini)",
    "titoloBase": "Pranzo/cena operatori interni",
    "variante": "Prezzo menu bambini",
    "descrizione": "Servizio Ufficiale TDA: Pranzo/cena operatori interni (Prezzo menu bambini) • Ripartizione: 40% Santo Stefano / 60% Iovino",
    "prezzo_unitario": 50,
    "unita_misura": "corpo",
    "unitaLabel": "per operatore interno",
    "splitLabel": "40% Santo Stefano / 60% Iovino",
    "splitKey": "40_60",
    "immagine": "https://laterradegliaranci.it/wp-content/uploads/2024/07/sala-terradegliaranci.jpg",
    "costo_fornitore": 0,
    "fase_evento": "sala_tufo"
  },
  {
    "id": "ext03",
    "code": "EXT03",
    "categoria": "Extra ricevimento",
    "nome": "Pranzo/cena operatori esterni (Prezzo adulti)",
    "titoloBase": "Pranzo/cena operatori esterni",
    "variante": "Prezzo adulti",
    "descrizione": "Servizio Ufficiale TDA: Pranzo/cena operatori esterni (Prezzo adulti) • Ripartizione: 40% Santo Stefano / 60% Iovino",
    "prezzo_unitario": 140,
    "unita_misura": "corpo",
    "unitaLabel": "per operatore esterno",
    "splitLabel": "40% Santo Stefano / 60% Iovino",
    "splitKey": "40_60",
    "immagine": "https://laterradegliaranci.it/wp-content/uploads/2024/07/sala-terradegliaranci.jpg",
    "costo_fornitore": 0,
    "fase_evento": "sala_tufo"
  },
  {
    "id": "ext04",
    "code": "EXT04",
    "categoria": "Extra ricevimento",
    "nome": "Parcheggio (Fino a 40 auto)",
    "titoloBase": "Parcheggio",
    "variante": "Fino a 40 auto",
    "descrizione": "Servizio Ufficiale TDA: Parcheggio (Fino a 40 auto) • Ripartizione: 100% Santo Stefano",
    "prezzo_unitario": 300,
    "unita_misura": "corpo",
    "unitaLabel": "per evento",
    "splitLabel": "100% Santo Stefano",
    "splitKey": "ss100",
    "immagine": "https://laterradegliaranci.it/wp-content/uploads/2024/07/sala-terradegliaranci.jpg",
    "costo_fornitore": 0,
    "fase_evento": "sala_tufo"
  },
  {
    "id": "ext05",
    "code": "EXT05",
    "categoria": "Extra ricevimento",
    "nome": "Parcheggio (40-60 auto)",
    "titoloBase": "Parcheggio",
    "variante": "40-60 auto",
    "descrizione": "Servizio Ufficiale TDA: Parcheggio (40-60 auto) • Ripartizione: 100% Santo Stefano",
    "prezzo_unitario": 450,
    "unita_misura": "corpo",
    "unitaLabel": "per evento",
    "splitLabel": "100% Santo Stefano",
    "splitKey": "ss100",
    "immagine": "https://laterradegliaranci.it/wp-content/uploads/2024/07/sala-terradegliaranci.jpg",
    "costo_fornitore": 0,
    "fase_evento": "sala_tufo"
  },
  {
    "id": "ext06",
    "code": "EXT06",
    "categoria": "Extra ricevimento",
    "nome": "Parcheggio (60-80 auto)",
    "titoloBase": "Parcheggio",
    "variante": "60-80 auto",
    "descrizione": "Servizio Ufficiale TDA: Parcheggio (60-80 auto) • Ripartizione: 100% Santo Stefano",
    "prezzo_unitario": 600,
    "unita_misura": "corpo",
    "unitaLabel": "per evento",
    "splitLabel": "100% Santo Stefano",
    "splitKey": "ss100",
    "immagine": "https://laterradegliaranci.it/wp-content/uploads/2024/07/sala-terradegliaranci.jpg",
    "costo_fornitore": 0,
    "fase_evento": "sala_tufo"
  },
  {
    "id": "ext07",
    "code": "EXT07",
    "categoria": "Extra ricevimento",
    "nome": "Supplemento parcheggio after dinner (Parcheggio aperto per after)",
    "titoloBase": "Supplemento parcheggio after dinner",
    "variante": "Parcheggio aperto per after",
    "descrizione": "Servizio Ufficiale TDA: Supplemento parcheggio after dinner (Parcheggio aperto per after) • Ripartizione: 100% Santo Stefano",
    "prezzo_unitario": 150,
    "unita_misura": "corpo",
    "unitaLabel": "per evento",
    "splitLabel": "100% Santo Stefano",
    "splitKey": "ss100",
    "immagine": "https://laterradegliaranci.it/wp-content/uploads/2024/07/sala-terradegliaranci.jpg",
    "costo_fornitore": 0,
    "fase_evento": "sala_tufo"
  },
  {
    "id": "ext08",
    "code": "EXT08",
    "categoria": "Extra ricevimento",
    "nome": "Service musica (Postazione cena e dance con fonico)",
    "titoloBase": "Service musica",
    "variante": "Postazione cena e dance con fonico",
    "descrizione": "Servizio Ufficiale TDA: Service musica (Postazione cena e dance con fonico) • Ripartizione: €50 Santo Stefano, resto Iovino",
    "prezzo_unitario": 500,
    "unita_misura": "corpo",
    "unitaLabel": "per servizio",
    "splitLabel": "€50 Santo Stefano, resto Iovino",
    "splitKey": "ss50",
    "immagine": "https://laterradegliaranci.it/wp-content/uploads/2024/07/sala-tufo.jpg",
    "costo_fornitore": 0,
    "fase_evento": "sala_tufo"
  },
  {
    "id": "ext09",
    "code": "EXT09",
    "categoria": "Extra ricevimento",
    "nome": "Service musica (Postazione aggiuntiva)",
    "titoloBase": "Service musica",
    "variante": "Postazione aggiuntiva",
    "descrizione": "Servizio Ufficiale TDA: Service musica (Postazione aggiuntiva) • Ripartizione: €50 Santo Stefano, resto Iovino",
    "prezzo_unitario": 100,
    "unita_misura": "corpo",
    "unitaLabel": "per postazione",
    "splitLabel": "€50 Santo Stefano, resto Iovino",
    "splitKey": "ss50",
    "immagine": "https://laterradegliaranci.it/wp-content/uploads/2024/07/sala-tufo.jpg",
    "costo_fornitore": 0,
    "fase_evento": "sala_tufo"
  },
  {
    "id": "ext10",
    "code": "EXT10",
    "categoria": "Extra ricevimento",
    "nome": "SIAE (Pagamento delegato alla struttura)",
    "titoloBase": "SIAE",
    "variante": "Pagamento delegato alla struttura",
    "descrizione": "Servizio Ufficiale TDA: SIAE (Pagamento delegato alla struttura) • Ripartizione: 100% Santo Stefano",
    "prezzo_unitario": 300,
    "unita_misura": "corpo",
    "unitaLabel": "per evento",
    "splitLabel": "100% Santo Stefano",
    "splitKey": "ss100",
    "immagine": "https://laterradegliaranci.it/wp-content/uploads/2024/07/sala-terradegliaranci.jpg",
    "costo_fornitore": 0,
    "fase_evento": "sala_tufo"
  },
  {
    "id": "ext11",
    "code": "EXT11",
    "categoria": "Allestimenti",
    "nome": "Allestimenti non compresi (Mise en place / sedute / segnaposto / attrezzature)",
    "titoloBase": "Allestimenti non compresi",
    "variante": "Mise en place / sedute / segnaposto / attrezzature",
    "descrizione": "Servizio Ufficiale TDA: Allestimenti non compresi (Mise en place / sedute / segnaposto / attrezzature) • Ripartizione: 100% Iovino",
    "prezzo_unitario": 0,
    "unita_misura": "corpo",
    "unitaLabel": "da quotare",
    "splitLabel": "100% Iovino",
    "splitKey": "i100",
    "immagine": "https://laterradegliaranci.it/wp-content/uploads/2024/07/sala-terradegliaranci.jpg",
    "costo_fornitore": 0,
    "fase_evento": "generale"
  },
  {
    "id": "ext12",
    "code": "EXT12",
    "categoria": "Rito in villa",
    "nome": "Rito in Villa (In giardino)",
    "titoloBase": "Rito in Villa",
    "variante": "In giardino",
    "descrizione": "Servizio Ufficiale TDA: Rito in Villa (In giardino) • Ripartizione: €100 Santo Stefano, resto Iovino",
    "prezzo_unitario": 800,
    "unita_misura": "corpo",
    "unitaLabel": "per evento",
    "splitLabel": "€100 Santo Stefano, resto Iovino",
    "splitKey": "ss100fixed",
    "immagine": "https://laterradegliaranci.it/wp-content/uploads/2024/06/giardino-promesse.jpg",
    "costo_fornitore": 0,
    "fase_evento": "rito"
  },
  {
    "id": "ext13",
    "code": "EXT13",
    "categoria": "Rito in villa",
    "nome": "Rito in Villa (In sala)",
    "titoloBase": "Rito in Villa",
    "variante": "In sala",
    "descrizione": "Servizio Ufficiale TDA: Rito in Villa (In sala) • Ripartizione: €100 Santo Stefano, resto Iovino",
    "prezzo_unitario": 500,
    "unita_misura": "corpo",
    "unitaLabel": "per evento",
    "splitLabel": "€100 Santo Stefano, resto Iovino",
    "splitKey": "ss100fixed",
    "immagine": "https://laterradegliaranci.it/wp-content/uploads/2024/06/giardino-promesse.jpg",
    "costo_fornitore": 0,
    "fase_evento": "rito"
  },
  {
    "id": "ext14",
    "code": "EXT14",
    "categoria": "Rito in villa",
    "nome": "Percorso con cordolo floreale (In sostituzione del tappeto)",
    "titoloBase": "Percorso con cordolo floreale",
    "variante": "In sostituzione del tappeto",
    "descrizione": "Servizio Ufficiale TDA: Percorso con cordolo floreale (In sostituzione del tappeto) • Ripartizione: €100 Santo Stefano, resto Iovino",
    "prezzo_unitario": 250,
    "unita_misura": "corpo",
    "unitaLabel": "per evento",
    "splitLabel": "€100 Santo Stefano, resto Iovino",
    "splitKey": "ss100fixed",
    "immagine": "https://laterradegliaranci.it/wp-content/uploads/2024/06/giardino-promesse.jpg",
    "costo_fornitore": 0,
    "fase_evento": "rito"
  },
  {
    "id": "ext15",
    "code": "EXT15",
    "categoria": "Rito in villa",
    "nome": "Preparazione degli sposi (Prima del rito)",
    "titoloBase": "Preparazione degli sposi",
    "variante": "Prima del rito",
    "descrizione": "Servizio Ufficiale TDA: Preparazione degli sposi (Prima del rito) • Ripartizione: €100 Santo Stefano, resto Iovino",
    "prezzo_unitario": 200,
    "unita_misura": "corpo",
    "unitaLabel": "per evento",
    "splitLabel": "€100 Santo Stefano, resto Iovino",
    "splitKey": "ss100fixed",
    "immagine": "https://laterradegliaranci.it/wp-content/uploads/2024/06/giardino-promesse.jpg",
    "costo_fornitore": 0,
    "fase_evento": "rito"
  },
  {
    "id": "ext16",
    "code": "EXT16",
    "categoria": "Rito in villa",
    "nome": "Celebrante (Prezzo base)",
    "titoloBase": "Celebrante",
    "variante": "Prezzo base",
    "descrizione": "Servizio Ufficiale TDA: Celebrante (Prezzo base) • Ripartizione: €100 Santo Stefano, resto Iovino",
    "prezzo_unitario": 500,
    "unita_misura": "corpo",
    "unitaLabel": "per evento",
    "splitLabel": "€100 Santo Stefano, resto Iovino",
    "splitKey": "ss100fixed",
    "immagine": "https://laterradegliaranci.it/wp-content/uploads/2024/06/giardino-promesse.jpg",
    "costo_fornitore": 0,
    "fase_evento": "rito"
  },
  {
    "id": "ext17",
    "code": "EXT17",
    "categoria": "Antipasto / pranzo in giardino",
    "nome": "Antipasto servito al tavolo in giardino (Servito al tavolo)",
    "titoloBase": "Antipasto servito al tavolo in giardino",
    "variante": "Servito al tavolo",
    "descrizione": "Servizio Ufficiale TDA: Antipasto servito al tavolo in giardino (Servito al tavolo) • Ripartizione: 40% Santo Stefano / 60% Iovino",
    "prezzo_unitario": 5,
    "unita_misura": "pax",
    "unitaLabel": "per ospite",
    "splitLabel": "40% Santo Stefano / 60% Iovino",
    "splitKey": "40_60",
    "immagine": "https://laterradegliaranci.it/wp-content/uploads/2024/06/giardino-promesse.jpg",
    "costo_fornitore": 0,
    "fase_evento": "agrumeto"
  },
  {
    "id": "ext18",
    "code": "EXT18",
    "categoria": "Antipasto / pranzo in giardino",
    "nome": "Pranzo/cena in giardino (Servito al tavolo)",
    "titoloBase": "Pranzo/cena in giardino",
    "variante": "Servito al tavolo",
    "descrizione": "Servizio Ufficiale TDA: Pranzo/cena in giardino (Servito al tavolo) • Ripartizione: 40% Santo Stefano / 60% Iovino",
    "prezzo_unitario": 10,
    "unita_misura": "pax",
    "unitaLabel": "per ospite",
    "splitLabel": "40% Santo Stefano / 60% Iovino",
    "splitKey": "40_60",
    "immagine": "https://laterradegliaranci.it/wp-content/uploads/2024/06/giardino-promesse.jpg",
    "costo_fornitore": 0,
    "fase_evento": "agrumeto"
  },
  {
    "id": "ext19",
    "code": "EXT19",
    "categoria": "Antipasto / pranzo in giardino",
    "nome": "Tavolo imperiale in giardino con runner (Tavolo imperiale)",
    "titoloBase": "Tavolo imperiale in giardino con runner",
    "variante": "Tavolo imperiale",
    "descrizione": "Servizio Ufficiale TDA: Tavolo imperiale in giardino con runner (Tavolo imperiale) • Ripartizione: 40% Santo Stefano / 60% Iovino",
    "prezzo_unitario": 10,
    "unita_misura": "pax",
    "unitaLabel": "per ospite",
    "splitLabel": "40% Santo Stefano / 60% Iovino",
    "splitKey": "40_60",
    "immagine": "https://laterradegliaranci.it/wp-content/uploads/2024/06/giardino-promesse.jpg",
    "costo_fornitore": 0,
    "fase_evento": "agrumeto"
  },
  {
    "id": "ext20",
    "code": "EXT20",
    "categoria": "Strutture e coreografie",
    "nome": "Tensostruttura completa (Chiusura superiore e laterale con riscaldamento)",
    "titoloBase": "Tensostruttura completa",
    "variante": "Chiusura superiore e laterale con riscaldamento",
    "descrizione": "Servizio Ufficiale TDA: Tensostruttura completa (Chiusura superiore e laterale con riscaldamento) • Ripartizione: 100% Santo Stefano",
    "prezzo_unitario": 3300,
    "unita_misura": "corpo",
    "unitaLabel": "per evento",
    "splitLabel": "100% Santo Stefano",
    "splitKey": "ss100",
    "immagine": "https://laterradegliaranci.it/wp-content/uploads/2024/07/sala-terradegliaranci.jpg",
    "costo_fornitore": 0,
    "fase_evento": "generale"
  },
  {
    "id": "ext21",
    "code": "EXT21",
    "categoria": "Strutture e coreografie",
    "nome": "Tensostruttura parziale (Chiusura superiore)",
    "titoloBase": "Tensostruttura parziale",
    "variante": "Chiusura superiore",
    "descrizione": "Servizio Ufficiale TDA: Tensostruttura parziale (Chiusura superiore) • Ripartizione: 100% Santo Stefano",
    "prezzo_unitario": 2500,
    "unita_misura": "corpo",
    "unitaLabel": "per evento",
    "splitLabel": "100% Santo Stefano",
    "splitKey": "ss100",
    "immagine": "https://laterradegliaranci.it/wp-content/uploads/2024/07/sala-terradegliaranci.jpg",
    "costo_fornitore": 0,
    "fase_evento": "generale"
  },
  {
    "id": "ext22",
    "code": "EXT22",
    "categoria": "Strutture e coreografie",
    "nome": "Fuochi freddi (Taglio torta)",
    "titoloBase": "Fuochi freddi",
    "variante": "Taglio torta",
    "descrizione": "Servizio Ufficiale TDA: Fuochi freddi (Taglio torta) • Ripartizione: €50 Santo Stefano, resto Iovino",
    "prezzo_unitario": 500,
    "unita_misura": "corpo",
    "unitaLabel": "per evento",
    "splitLabel": "€50 Santo Stefano, resto Iovino",
    "splitKey": "ss50",
    "immagine": "https://laterradegliaranci.it/wp-content/uploads/2024/07/sala-terradegliaranci.jpg",
    "costo_fornitore": 0,
    "fase_evento": "torta"
  },
  {
    "id": "ext23",
    "code": "EXT23",
    "categoria": "After Party",
    "nome": "After Party Sala Tufo (Fino a 50 partecipanti)",
    "titoloBase": "After Party Sala Tufo",
    "variante": "Fino a 50 partecipanti",
    "descrizione": "Servizio Ufficiale TDA: After Party Sala Tufo (Fino a 50 partecipanti) • Ripartizione: SS: 40% di €1.750; Iovino: 60% di €1.750 + €250",
    "prezzo_unitario": 2000,
    "unita_misura": "corpo",
    "unitaLabel": "per evento",
    "splitLabel": "SS: 40% di €1.750; Iovino: 60% di €1.750 + €250",
    "splitKey": "after",
    "immagine": "https://laterradegliaranci.it/wp-content/uploads/2024/07/sala-tufo.jpg",
    "costo_fornitore": 0,
    "fase_evento": "after_party"
  },
  {
    "id": "ext24",
    "code": "EXT24",
    "categoria": "After Party",
    "nome": "After Party extra partecipanti (Oltre 50 partecipanti)",
    "titoloBase": "After Party extra partecipanti",
    "variante": "Oltre 50 partecipanti",
    "descrizione": "Servizio Ufficiale TDA: After Party extra partecipanti (Oltre 50 partecipanti) • Ripartizione: 40% Santo Stefano / 60% Iovino",
    "prezzo_unitario": 30,
    "unita_misura": "pax",
    "unitaLabel": "per persona extra",
    "splitLabel": "40% Santo Stefano / 60% Iovino",
    "splitKey": "40_60",
    "immagine": "https://laterradegliaranci.it/wp-content/uploads/2024/07/sala-tufo.jpg",
    "costo_fornitore": 0,
    "fase_evento": "after_party"
  },
  {
    "id": "ext25",
    "code": "EXT25",
    "categoria": "Service luci e palchi",
    "nome": "Illuminazione musicisti (Extra luci)",
    "titoloBase": "Illuminazione musicisti",
    "variante": "Extra luci",
    "descrizione": "Servizio Ufficiale TDA: Illuminazione musicisti (Extra luci) • Ripartizione: €25 Santo Stefano, resto Iovino",
    "prezzo_unitario": 150,
    "unita_misura": "corpo",
    "unitaLabel": "per servizio",
    "splitLabel": "€25 Santo Stefano, resto Iovino",
    "splitKey": "ss25",
    "immagine": "https://laterradegliaranci.it/wp-content/uploads/2024/07/sala-tufo.jpg",
    "costo_fornitore": 0,
    "fase_evento": "generale"
  },
  {
    "id": "ext26",
    "code": "EXT26",
    "categoria": "Service luci e palchi",
    "nome": "Spot colorati in giardino (Minimo 10)",
    "titoloBase": "Spot colorati in giardino",
    "variante": "Minimo 10",
    "descrizione": "Servizio Ufficiale TDA: Spot colorati in giardino (Minimo 10) • Ripartizione: Fino a €25 Santo Stefano, resto Iovino",
    "prezzo_unitario": 20,
    "unita_misura": "corpo",
    "unitaLabel": "cad.",
    "splitLabel": "Fino a €25 Santo Stefano, resto Iovino",
    "splitKey": "ss25cap",
    "immagine": "https://laterradegliaranci.it/wp-content/uploads/2024/06/giardino-promesse.jpg",
    "costo_fornitore": 0,
    "fase_evento": "agrumeto"
  },
  {
    "id": "ext27",
    "code": "EXT27",
    "categoria": "Service luci e palchi",
    "nome": "Illuminazione dance floor (2 teste mobili)",
    "titoloBase": "Illuminazione dance floor",
    "variante": "2 teste mobili",
    "descrizione": "Servizio Ufficiale TDA: Illuminazione dance floor (2 teste mobili) • Ripartizione: €25 Santo Stefano, resto Iovino",
    "prezzo_unitario": 200,
    "unita_misura": "corpo",
    "unitaLabel": "per servizio",
    "splitLabel": "€25 Santo Stefano, resto Iovino",
    "splitKey": "ss25",
    "immagine": "https://laterradegliaranci.it/wp-content/uploads/2024/07/sala-tufo.jpg",
    "costo_fornitore": 0,
    "fase_evento": "generale"
  },
  {
    "id": "ext28",
    "code": "EXT28",
    "categoria": "Service luci e palchi",
    "nome": "Sfera a specchi (Extra luce)",
    "titoloBase": "Sfera a specchi",
    "variante": "Extra luce",
    "descrizione": "Servizio Ufficiale TDA: Sfera a specchi (Extra luce) • Ripartizione: €25 Santo Stefano, resto Iovino",
    "prezzo_unitario": 300,
    "unita_misura": "corpo",
    "unitaLabel": "per servizio",
    "splitLabel": "€25 Santo Stefano, resto Iovino",
    "splitKey": "ss25",
    "immagine": "https://laterradegliaranci.it/wp-content/uploads/2024/07/sala-tufo.jpg",
    "costo_fornitore": 0,
    "fase_evento": "generale"
  },
  {
    "id": "ext29",
    "code": "EXT29",
    "categoria": "Service luci e palchi",
    "nome": "Palco per band (Quotazione personalizzata)",
    "titoloBase": "Palco per band",
    "variante": "Quotazione personalizzata",
    "descrizione": "Servizio Ufficiale TDA: Palco per band (Quotazione personalizzata) • Ripartizione: €25 Santo Stefano, resto Iovino",
    "prezzo_unitario": 0,
    "unita_misura": "corpo",
    "unitaLabel": "da quotare",
    "splitLabel": "€25 Santo Stefano, resto Iovino",
    "splitKey": "ss25",
    "immagine": "https://laterradegliaranci.it/wp-content/uploads/2024/07/sala-tufo.jpg",
    "costo_fornitore": 0,
    "fase_evento": "generale"
  },
  {
    "id": "ext30",
    "code": "EXT30",
    "categoria": "Servizi personalizzati",
    "nome": "Parfum bar (80 cadeaux)",
    "titoloBase": "Parfum bar",
    "variante": "80 cadeaux",
    "descrizione": "Servizio Ufficiale TDA: Parfum bar (80 cadeaux) • Ripartizione: €100 Santo Stefano, resto Iovino",
    "prezzo_unitario": 1100,
    "unita_misura": "corpo",
    "unitaLabel": "per evento",
    "splitLabel": "€100 Santo Stefano, resto Iovino",
    "splitKey": "ss100fixed",
    "immagine": "https://laterradegliaranci.it/wp-content/uploads/2024/07/sala-terradegliaranci.jpg",
    "costo_fornitore": 0,
    "fase_evento": "generale"
  },
  {
    "id": "ext31",
    "code": "EXT31",
    "categoria": "Servizi personalizzati",
    "nome": "Parfum bar (120 cadeaux)",
    "titoloBase": "Parfum bar",
    "variante": "120 cadeaux",
    "descrizione": "Servizio Ufficiale TDA: Parfum bar (120 cadeaux) • Ripartizione: €100 Santo Stefano, resto Iovino",
    "prezzo_unitario": 1300,
    "unita_misura": "corpo",
    "unitaLabel": "per evento",
    "splitLabel": "€100 Santo Stefano, resto Iovino",
    "splitKey": "ss100fixed",
    "immagine": "https://laterradegliaranci.it/wp-content/uploads/2024/07/sala-terradegliaranci.jpg",
    "costo_fornitore": 0,
    "fase_evento": "generale"
  },
  {
    "id": "ext32",
    "code": "EXT32",
    "categoria": "Servizi personalizzati",
    "nome": "Parfum bar (180 cadeaux)",
    "titoloBase": "Parfum bar",
    "variante": "180 cadeaux",
    "descrizione": "Servizio Ufficiale TDA: Parfum bar (180 cadeaux) • Ripartizione: €100 Santo Stefano, resto Iovino",
    "prezzo_unitario": 1600,
    "unita_misura": "corpo",
    "unitaLabel": "per evento",
    "splitLabel": "€100 Santo Stefano, resto Iovino",
    "splitKey": "ss100fixed",
    "immagine": "https://laterradegliaranci.it/wp-content/uploads/2024/07/sala-terradegliaranci.jpg",
    "costo_fornitore": 0,
    "fase_evento": "generale"
  },
  {
    "id": "ext33",
    "code": "EXT33",
    "categoria": "Servizi personalizzati",
    "nome": "Angolo scarpe comode (Ballerine e/o infradito)",
    "titoloBase": "Angolo scarpe comode",
    "variante": "Ballerine e/o infradito",
    "descrizione": "Servizio Ufficiale TDA: Angolo scarpe comode (Ballerine e/o infradito) • Ripartizione: 100% Iovino",
    "prezzo_unitario": 10,
    "unita_misura": "corpo",
    "unitaLabel": "per paio",
    "splitLabel": "100% Iovino",
    "splitKey": "i100",
    "immagine": "https://laterradegliaranci.it/wp-content/uploads/2024/07/sala-terradegliaranci.jpg",
    "costo_fornitore": 0,
    "fase_evento": "generale"
  },
  {
    "id": "ext34",
    "code": "EXT34",
    "categoria": "Servizi personalizzati",
    "nome": "Partecipazioni, segnaposto e bomboniere (Personalizzati)",
    "titoloBase": "Partecipazioni, segnaposto e bomboniere",
    "variante": "Personalizzati",
    "descrizione": "Servizio Ufficiale TDA: Partecipazioni, segnaposto e bomboniere (Personalizzati) • Ripartizione: 100% Iovino",
    "prezzo_unitario": 0,
    "unita_misura": "corpo",
    "unitaLabel": "da quotare",
    "splitLabel": "100% Iovino",
    "splitKey": "i100",
    "immagine": "https://laterradegliaranci.it/wp-content/uploads/2024/07/sala-terradegliaranci.jpg",
    "costo_fornitore": 0,
    "fase_evento": "generale"
  },
  {
    "id": "ext35",
    "code": "EXT35",
    "categoria": "Servizi personalizzati",
    "nome": "Pet sitter (Assistenza evento)",
    "titoloBase": "Pet sitter",
    "variante": "Assistenza evento",
    "descrizione": "Servizio Ufficiale TDA: Pet sitter (Assistenza evento) • Ripartizione: €25 Santo Stefano, resto Iovino",
    "prezzo_unitario": 250,
    "unita_misura": "corpo",
    "unitaLabel": "per evento",
    "splitLabel": "€25 Santo Stefano, resto Iovino",
    "splitKey": "ss25",
    "immagine": "https://laterradegliaranci.it/wp-content/uploads/2024/07/sala-terradegliaranci.jpg",
    "costo_fornitore": 0,
    "fase_evento": "generale"
  },
  {
    "id": "ext36",
    "code": "EXT36",
    "categoria": "Servizi personalizzati",
    "nome": "Disegni live (100 caricature)",
    "titoloBase": "Disegni live",
    "variante": "100 caricature",
    "descrizione": "Servizio Ufficiale TDA: Disegni live (100 caricature) • Ripartizione: €50 Santo Stefano, resto Iovino",
    "prezzo_unitario": 500,
    "unita_misura": "corpo",
    "unitaLabel": "per evento",
    "splitLabel": "€50 Santo Stefano, resto Iovino",
    "splitKey": "ss50",
    "immagine": "https://laterradegliaranci.it/wp-content/uploads/2024/07/sala-terradegliaranci.jpg",
    "costo_fornitore": 0,
    "fase_evento": "generale"
  },
  {
    "id": "ext37",
    "code": "EXT37",
    "categoria": "Servizi personalizzati",
    "nome": "Disegni live (Live sketching - formula intrattenimento 3 ore)",
    "titoloBase": "Disegni live",
    "variante": "Live sketching - formula intrattenimento 3 ore",
    "descrizione": "Servizio Ufficiale TDA: Disegni live (Live sketching - formula intrattenimento 3 ore) • Ripartizione: €50 Santo Stefano, resto Iovino",
    "prezzo_unitario": 550,
    "unita_misura": "corpo",
    "unitaLabel": "per evento",
    "splitLabel": "€50 Santo Stefano, resto Iovino",
    "splitKey": "ss50",
    "immagine": "https://laterradegliaranci.it/wp-content/uploads/2024/07/sala-terradegliaranci.jpg",
    "costo_fornitore": 0,
    "fase_evento": "generale"
  },
  {
    "id": "ext38",
    "code": "EXT38",
    "categoria": "Servizi personalizzati",
    "nome": "Disegni live (Live sketching - formula evento intero)",
    "titoloBase": "Disegni live",
    "variante": "Live sketching - formula evento intero",
    "descrizione": "Servizio Ufficiale TDA: Disegni live (Live sketching - formula evento intero) • Ripartizione: €50 Santo Stefano, resto Iovino",
    "prezzo_unitario": 1000,
    "unita_misura": "corpo",
    "unitaLabel": "per evento",
    "splitLabel": "€50 Santo Stefano, resto Iovino",
    "splitKey": "ss50",
    "immagine": "https://laterradegliaranci.it/wp-content/uploads/2024/07/sala-terradegliaranci.jpg",
    "costo_fornitore": 0,
    "fase_evento": "generale"
  },
  {
    "id": "ext39",
    "code": "EXT39",
    "categoria": "Servizi personalizzati",
    "nome": "Live painting (Fino a 70 pezzi)",
    "titoloBase": "Live painting",
    "variante": "Fino a 70 pezzi",
    "descrizione": "Servizio Ufficiale TDA: Live painting (Fino a 70 pezzi) • Ripartizione: €50 Santo Stefano, resto Iovino",
    "prezzo_unitario": 1100,
    "unita_misura": "corpo",
    "unitaLabel": "per evento",
    "splitLabel": "€50 Santo Stefano, resto Iovino",
    "splitKey": "ss50",
    "immagine": "https://laterradegliaranci.it/wp-content/uploads/2024/07/sala-terradegliaranci.jpg",
    "costo_fornitore": 0,
    "fase_evento": "generale"
  },
  {
    "id": "ext40",
    "code": "EXT40",
    "categoria": "Servizi personalizzati",
    "nome": "Live painting (Fino a 100 pezzi)",
    "titoloBase": "Live painting",
    "variante": "Fino a 100 pezzi",
    "descrizione": "Servizio Ufficiale TDA: Live painting (Fino a 100 pezzi) • Ripartizione: €50 Santo Stefano, resto Iovino",
    "prezzo_unitario": 1450,
    "unita_misura": "corpo",
    "unitaLabel": "per evento",
    "splitLabel": "€50 Santo Stefano, resto Iovino",
    "splitKey": "ss50",
    "immagine": "https://laterradegliaranci.it/wp-content/uploads/2024/07/sala-terradegliaranci.jpg",
    "costo_fornitore": 0,
    "fase_evento": "generale"
  },
  {
    "id": "ext41",
    "code": "EXT41",
    "categoria": "Servizi personalizzati",
    "nome": "Live painting (Fino a 160 pezzi)",
    "titoloBase": "Live painting",
    "variante": "Fino a 160 pezzi",
    "descrizione": "Servizio Ufficiale TDA: Live painting (Fino a 160 pezzi) • Ripartizione: €50 Santo Stefano, resto Iovino",
    "prezzo_unitario": 1800,
    "unita_misura": "corpo",
    "unitaLabel": "per evento",
    "splitLabel": "€50 Santo Stefano, resto Iovino",
    "splitKey": "ss50",
    "immagine": "https://laterradegliaranci.it/wp-content/uploads/2024/07/sala-terradegliaranci.jpg",
    "costo_fornitore": 0,
    "fase_evento": "generale"
  },
  {
    "id": "ext42",
    "code": "EXT42",
    "categoria": "Servizi personalizzati",
    "nome": "Bridal Assistant (Pacchetto Bridal Corallo)",
    "titoloBase": "Bridal Assistant",
    "variante": "Pacchetto Bridal Corallo",
    "descrizione": "Servizio Ufficiale TDA: Bridal Assistant (Pacchetto Bridal Corallo) • Ripartizione: €50 Santo Stefano, resto Iovino",
    "prezzo_unitario": 270,
    "unita_misura": "corpo",
    "unitaLabel": "per evento",
    "splitLabel": "€50 Santo Stefano, resto Iovino",
    "splitKey": "ss50",
    "immagine": "https://laterradegliaranci.it/wp-content/uploads/2024/07/sala-terradegliaranci.jpg",
    "costo_fornitore": 0,
    "fase_evento": "generale"
  },
  {
    "id": "ext43",
    "code": "EXT43",
    "categoria": "Servizi personalizzati",
    "nome": "Bridal Assistant (Pacchetto Bridal Swarovski)",
    "titoloBase": "Bridal Assistant",
    "variante": "Pacchetto Bridal Swarovski",
    "descrizione": "Servizio Ufficiale TDA: Bridal Assistant (Pacchetto Bridal Swarovski) • Ripartizione: €50 Santo Stefano, resto Iovino",
    "prezzo_unitario": 450,
    "unita_misura": "corpo",
    "unitaLabel": "per evento",
    "splitLabel": "€50 Santo Stefano, resto Iovino",
    "splitKey": "ss50",
    "immagine": "https://laterradegliaranci.it/wp-content/uploads/2024/07/sala-terradegliaranci.jpg",
    "costo_fornitore": 0,
    "fase_evento": "generale"
  },
  {
    "id": "ext44",
    "code": "EXT44",
    "categoria": "Servizi personalizzati",
    "nome": "Bridal Assistant (Pacchetto Bridal Diamond)",
    "titoloBase": "Bridal Assistant",
    "variante": "Pacchetto Bridal Diamond",
    "descrizione": "Servizio Ufficiale TDA: Bridal Assistant (Pacchetto Bridal Diamond) • Ripartizione: €50 Santo Stefano, resto Iovino",
    "prezzo_unitario": 720,
    "unita_misura": "corpo",
    "unitaLabel": "per evento",
    "splitLabel": "€50 Santo Stefano, resto Iovino",
    "splitKey": "ss50",
    "immagine": "https://laterradegliaranci.it/wp-content/uploads/2024/07/sala-terradegliaranci.jpg",
    "costo_fornitore": 0,
    "fase_evento": "generale"
  },
  {
    "id": "ext45",
    "code": "EXT45",
    "categoria": "Servizi da quotare",
    "nome": "Matrimonio sostenibile (Impatto zero / basso impatto)",
    "titoloBase": "Matrimonio sostenibile",
    "variante": "Impatto zero / basso impatto",
    "descrizione": "Servizio Ufficiale TDA: Matrimonio sostenibile (Impatto zero / basso impatto) • Ripartizione: Da quotare / da definire",
    "prezzo_unitario": 0,
    "unita_misura": "corpo",
    "unitaLabel": "da quotare",
    "splitLabel": "Da quotare / da definire",
    "splitKey": "manual",
    "immagine": "https://laterradegliaranci.it/wp-content/uploads/2024/07/sala-terradegliaranci.jpg",
    "costo_fornitore": 0,
    "fase_evento": "generale"
  },
  {
    "id": "ext46",
    "code": "EXT46",
    "categoria": "Servizi da quotare",
    "nome": "Invito digitale o wedding site (Personalizzato)",
    "titoloBase": "Invito digitale o wedding site",
    "variante": "Personalizzato",
    "descrizione": "Servizio Ufficiale TDA: Invito digitale o wedding site (Personalizzato) • Ripartizione: Da quotare / da definire",
    "prezzo_unitario": 0,
    "unita_misura": "corpo",
    "unitaLabel": "da quotare",
    "splitLabel": "Da quotare / da definire",
    "splitKey": "manual",
    "immagine": "https://laterradegliaranci.it/wp-content/uploads/2024/07/sala-terradegliaranci.jpg",
    "costo_fornitore": 0,
    "fase_evento": "generale"
  },
  {
    "id": "ext47",
    "code": "EXT47",
    "categoria": "Servizi da quotare",
    "nome": "Convenzioni (Alberghi / transfert / tour / esperienze)",
    "titoloBase": "Convenzioni",
    "variante": "Alberghi / transfert / tour / esperienze",
    "descrizione": "Servizio Ufficiale TDA: Convenzioni (Alberghi / transfert / tour / esperienze) • Ripartizione: Da quotare / da definire",
    "prezzo_unitario": 0,
    "unita_misura": "corpo",
    "unitaLabel": "da quotare",
    "splitLabel": "Da quotare / da definire",
    "splitKey": "manual",
    "immagine": "https://laterradegliaranci.it/wp-content/uploads/2024/07/sala-terradegliaranci.jpg",
    "costo_fornitore": 0,
    "fase_evento": "generale"
  },
  {
    "id": "ang01",
    "code": "ANG01",
    "categoria": "Angoli extra ricevimento",
    "nome": "Angolo Spritz (70-100 adulti)",
    "titoloBase": "Angolo Spritz",
    "variante": "70-100 adulti",
    "descrizione": "Servizio Ufficiale TDA: Angolo Spritz (70-100 adulti) • Ripartizione: €100 Santo Stefano sul totale evento, resto Iovino",
    "prezzo_unitario": 600,
    "unita_misura": "corpo",
    "unitaLabel": "per evento",
    "splitLabel": "€100 Santo Stefano sul totale evento, resto Iovino",
    "splitKey": "angle",
    "immagine": "https://laterradegliaranci.it/wp-content/uploads/2024/07/sala-terradegliaranci.jpg",
    "costo_fornitore": 0,
    "fase_evento": "agrumeto"
  },
  {
    "id": "ang02",
    "code": "ANG02",
    "categoria": "Angoli extra ricevimento",
    "nome": "Angolo Spritz (100-150 invitati)",
    "titoloBase": "Angolo Spritz",
    "variante": "100-150 invitati",
    "descrizione": "Servizio Ufficiale TDA: Angolo Spritz (100-150 invitati) • Ripartizione: €100 Santo Stefano sul totale evento, resto Iovino",
    "prezzo_unitario": 800,
    "unita_misura": "corpo",
    "unitaLabel": "per evento",
    "splitLabel": "€100 Santo Stefano sul totale evento, resto Iovino",
    "splitKey": "angle",
    "immagine": "https://laterradegliaranci.it/wp-content/uploads/2024/07/sala-terradegliaranci.jpg",
    "costo_fornitore": 0,
    "fase_evento": "agrumeto"
  },
  {
    "id": "ang03",
    "code": "ANG03",
    "categoria": "Angoli extra ricevimento",
    "nome": "Angolo Spritz (&gt;150 invitati)",
    "titoloBase": "Angolo Spritz",
    "variante": "&gt;150 invitati",
    "descrizione": "Servizio Ufficiale TDA: Angolo Spritz (&gt;150 invitati) • Ripartizione: €100 Santo Stefano sul totale evento, resto Iovino",
    "prezzo_unitario": 1000,
    "unita_misura": "corpo",
    "unitaLabel": "per evento",
    "splitLabel": "€100 Santo Stefano sul totale evento, resto Iovino",
    "splitKey": "angle",
    "immagine": "https://laterradegliaranci.it/wp-content/uploads/2024/07/sala-terradegliaranci.jpg",
    "costo_fornitore": 0,
    "fase_evento": "agrumeto"
  },
  {
    "id": "ang04",
    "code": "ANG04",
    "categoria": "Angoli extra ricevimento",
    "nome": "Champagneria (70-100 adulti)",
    "titoloBase": "Champagneria",
    "variante": "70-100 adulti",
    "descrizione": "Servizio Ufficiale TDA: Champagneria (70-100 adulti) • Ripartizione: €100 Santo Stefano sul totale evento, resto Iovino",
    "prezzo_unitario": 900,
    "unita_misura": "corpo",
    "unitaLabel": "per evento",
    "splitLabel": "€100 Santo Stefano sul totale evento, resto Iovino",
    "splitKey": "angle",
    "immagine": "https://laterradegliaranci.it/wp-content/uploads/2024/07/sala-terradegliaranci.jpg",
    "costo_fornitore": 0,
    "fase_evento": "agrumeto"
  },
  {
    "id": "ang05",
    "code": "ANG05",
    "categoria": "Angoli extra ricevimento",
    "nome": "Champagneria (100-150 invitati)",
    "titoloBase": "Champagneria",
    "variante": "100-150 invitati",
    "descrizione": "Servizio Ufficiale TDA: Champagneria (100-150 invitati) • Ripartizione: €100 Santo Stefano sul totale evento, resto Iovino",
    "prezzo_unitario": 1100,
    "unita_misura": "corpo",
    "unitaLabel": "per evento",
    "splitLabel": "€100 Santo Stefano sul totale evento, resto Iovino",
    "splitKey": "angle",
    "immagine": "https://laterradegliaranci.it/wp-content/uploads/2024/07/sala-terradegliaranci.jpg",
    "costo_fornitore": 0,
    "fase_evento": "agrumeto"
  },
  {
    "id": "ang06",
    "code": "ANG06",
    "categoria": "Angoli extra ricevimento",
    "nome": "Champagneria (&gt;150 invitati)",
    "titoloBase": "Champagneria",
    "variante": "&gt;150 invitati",
    "descrizione": "Servizio Ufficiale TDA: Champagneria (&gt;150 invitati) • Ripartizione: €100 Santo Stefano sul totale evento, resto Iovino",
    "prezzo_unitario": 1300,
    "unita_misura": "corpo",
    "unitaLabel": "per evento",
    "splitLabel": "€100 Santo Stefano sul totale evento, resto Iovino",
    "splitKey": "angle",
    "immagine": "https://laterradegliaranci.it/wp-content/uploads/2024/07/sala-terradegliaranci.jpg",
    "costo_fornitore": 0,
    "fase_evento": "agrumeto"
  },
  {
    "id": "ang07",
    "code": "ANG07",
    "categoria": "Angoli extra ricevimento",
    "nome": "Cocktail bar (Tutto il ricevimento)",
    "titoloBase": "Cocktail bar",
    "variante": "Tutto il ricevimento",
    "descrizione": "Servizio Ufficiale TDA: Cocktail bar (Tutto il ricevimento) • Ripartizione: €100 Santo Stefano sul totale evento, resto Iovino",
    "prezzo_unitario": 25,
    "unita_misura": "pax",
    "unitaLabel": "per adulto",
    "splitLabel": "€100 Santo Stefano sul totale evento, resto Iovino",
    "splitKey": "angle",
    "immagine": "https://laterradegliaranci.it/wp-content/uploads/2024/07/sala-terradegliaranci.jpg",
    "costo_fornitore": 0,
    "fase_evento": "agrumeto"
  },
  {
    "id": "ang08",
    "code": "ANG08",
    "categoria": "Angoli extra ricevimento",
    "nome": "Cocktail bar (Aperitivo o buffet dolci)",
    "titoloBase": "Cocktail bar",
    "variante": "Aperitivo o buffet dolci",
    "descrizione": "Servizio Ufficiale TDA: Cocktail bar (Aperitivo o buffet dolci) • Ripartizione: €100 Santo Stefano sul totale evento, resto Iovino",
    "prezzo_unitario": 10,
    "unita_misura": "pax",
    "unitaLabel": "per adulto",
    "splitLabel": "€100 Santo Stefano sul totale evento, resto Iovino",
    "splitKey": "angle",
    "immagine": "https://laterradegliaranci.it/wp-content/uploads/2024/07/sala-terradegliaranci.jpg",
    "costo_fornitore": 0,
    "fase_evento": "torta"
  },
  {
    "id": "ang09",
    "code": "ANG09",
    "categoria": "Angoli extra ricevimento",
    "nome": "Charcuterie di salumi (Jamon iberico fino a 100 ospiti)",
    "titoloBase": "Charcuterie di salumi",
    "variante": "Jamon iberico fino a 100 ospiti",
    "descrizione": "Servizio Ufficiale TDA: Charcuterie di salumi (Jamon iberico fino a 100 ospiti) • Ripartizione: €100 Santo Stefano sul totale evento, resto Iovino",
    "prezzo_unitario": 1000,
    "unita_misura": "corpo",
    "unitaLabel": "per evento",
    "splitLabel": "€100 Santo Stefano sul totale evento, resto Iovino",
    "splitKey": "angle",
    "immagine": "https://laterradegliaranci.it/wp-content/uploads/2024/07/sala-terradegliaranci.jpg",
    "costo_fornitore": 0,
    "fase_evento": "agrumeto"
  },
  {
    "id": "ang10",
    "code": "ANG10",
    "categoria": "Angoli extra ricevimento",
    "nome": "Charcuterie di salumi (Salumi regionali fino a 100 ospiti)",
    "titoloBase": "Charcuterie di salumi",
    "variante": "Salumi regionali fino a 100 ospiti",
    "descrizione": "Servizio Ufficiale TDA: Charcuterie di salumi (Salumi regionali fino a 100 ospiti) • Ripartizione: €100 Santo Stefano sul totale evento, resto Iovino",
    "prezzo_unitario": 600,
    "unita_misura": "corpo",
    "unitaLabel": "per evento",
    "splitLabel": "€100 Santo Stefano sul totale evento, resto Iovino",
    "splitKey": "angle",
    "immagine": "https://laterradegliaranci.it/wp-content/uploads/2024/07/sala-terradegliaranci.jpg",
    "costo_fornitore": 0,
    "fase_evento": "agrumeto"
  },
  {
    "id": "ang11",
    "code": "ANG11",
    "categoria": "Angoli extra ricevimento",
    "nome": "Degustazione crudi (Angolo Crudi)",
    "titoloBase": "Degustazione crudi",
    "variante": "Angolo Crudi",
    "descrizione": "Servizio Ufficiale TDA: Degustazione crudi (Angolo Crudi) • Ripartizione: €100 Santo Stefano sul totale evento, resto Iovino",
    "prezzo_unitario": 15,
    "unita_misura": "pax",
    "unitaLabel": "per ospite",
    "splitLabel": "€100 Santo Stefano sul totale evento, resto Iovino",
    "splitKey": "angle",
    "immagine": "https://laterradegliaranci.it/wp-content/uploads/2024/07/sala-terradegliaranci.jpg",
    "costo_fornitore": 0,
    "fase_evento": "agrumeto"
  },
  {
    "id": "ang12",
    "code": "ANG12",
    "categoria": "Angoli extra ricevimento",
    "nome": "Angolo caciocavallo impiccato (70-100 adulti)",
    "titoloBase": "Angolo caciocavallo impiccato",
    "variante": "70-100 adulti",
    "descrizione": "Servizio Ufficiale TDA: Angolo caciocavallo impiccato (70-100 adulti) • Ripartizione: €100 Santo Stefano sul totale evento, resto Iovino",
    "prezzo_unitario": 300,
    "unita_misura": "corpo",
    "unitaLabel": "per evento",
    "splitLabel": "€100 Santo Stefano sul totale evento, resto Iovino",
    "splitKey": "angle",
    "immagine": "https://laterradegliaranci.it/wp-content/uploads/2025/01/73dc0729e7c1e25df7e0fb1625acd89f.jpg",
    "costo_fornitore": 0,
    "fase_evento": "agrumeto"
  },
  {
    "id": "ang13",
    "code": "ANG13",
    "categoria": "Angoli extra ricevimento",
    "nome": "Angolo caciocavallo impiccato (100-150 invitati)",
    "titoloBase": "Angolo caciocavallo impiccato",
    "variante": "100-150 invitati",
    "descrizione": "Servizio Ufficiale TDA: Angolo caciocavallo impiccato (100-150 invitati) • Ripartizione: €100 Santo Stefano sul totale evento, resto Iovino",
    "prezzo_unitario": 400,
    "unita_misura": "corpo",
    "unitaLabel": "per evento",
    "splitLabel": "€100 Santo Stefano sul totale evento, resto Iovino",
    "splitKey": "angle",
    "immagine": "https://laterradegliaranci.it/wp-content/uploads/2025/01/73dc0729e7c1e25df7e0fb1625acd89f.jpg",
    "costo_fornitore": 0,
    "fase_evento": "agrumeto"
  },
  {
    "id": "ang14",
    "code": "ANG14",
    "categoria": "Angoli extra ricevimento",
    "nome": "Angolo caciocavallo impiccato (&gt;150 invitati)",
    "titoloBase": "Angolo caciocavallo impiccato",
    "variante": "&gt;150 invitati",
    "descrizione": "Servizio Ufficiale TDA: Angolo caciocavallo impiccato (&gt;150 invitati) • Ripartizione: €100 Santo Stefano sul totale evento, resto Iovino",
    "prezzo_unitario": 500,
    "unita_misura": "corpo",
    "unitaLabel": "per evento",
    "splitLabel": "€100 Santo Stefano sul totale evento, resto Iovino",
    "splitKey": "angle",
    "immagine": "https://laterradegliaranci.it/wp-content/uploads/2025/01/73dc0729e7c1e25df7e0fb1625acd89f.jpg",
    "costo_fornitore": 0,
    "fase_evento": "agrumeto"
  },
  {
    "id": "ang15",
    "code": "ANG15",
    "categoria": "Angoli extra ricevimento",
    "nome": "Degustazione delle olive (70-100 adulti)",
    "titoloBase": "Degustazione delle olive",
    "variante": "70-100 adulti",
    "descrizione": "Servizio Ufficiale TDA: Degustazione delle olive (70-100 adulti) • Ripartizione: €100 Santo Stefano sul totale evento, resto Iovino",
    "prezzo_unitario": 300,
    "unita_misura": "corpo",
    "unitaLabel": "per evento",
    "splitLabel": "€100 Santo Stefano sul totale evento, resto Iovino",
    "splitKey": "angle",
    "immagine": "https://laterradegliaranci.it/wp-content/uploads/2024/07/sala-terradegliaranci.jpg",
    "costo_fornitore": 0,
    "fase_evento": "agrumeto"
  },
  {
    "id": "ang16",
    "code": "ANG16",
    "categoria": "Angoli extra ricevimento",
    "nome": "Degustazione delle olive (100-150 invitati)",
    "titoloBase": "Degustazione delle olive",
    "variante": "100-150 invitati",
    "descrizione": "Servizio Ufficiale TDA: Degustazione delle olive (100-150 invitati) • Ripartizione: €100 Santo Stefano sul totale evento, resto Iovino",
    "prezzo_unitario": 400,
    "unita_misura": "corpo",
    "unitaLabel": "per evento",
    "splitLabel": "€100 Santo Stefano sul totale evento, resto Iovino",
    "splitKey": "angle",
    "immagine": "https://laterradegliaranci.it/wp-content/uploads/2024/07/sala-terradegliaranci.jpg",
    "costo_fornitore": 0,
    "fase_evento": "agrumeto"
  },
  {
    "id": "ang17",
    "code": "ANG17",
    "categoria": "Angoli extra ricevimento",
    "nome": "Alici del Cantabrico con crostini (70-100 adulti)",
    "titoloBase": "Alici del Cantabrico con crostini",
    "variante": "70-100 adulti",
    "descrizione": "Servizio Ufficiale TDA: Alici del Cantabrico con crostini (70-100 adulti) • Ripartizione: €100 Santo Stefano sul totale evento, resto Iovino",
    "prezzo_unitario": 400,
    "unita_misura": "corpo",
    "unitaLabel": "per evento",
    "splitLabel": "€100 Santo Stefano sul totale evento, resto Iovino",
    "splitKey": "angle",
    "immagine": "https://laterradegliaranci.it/wp-content/uploads/2024/07/sala-terradegliaranci.jpg",
    "costo_fornitore": 0,
    "fase_evento": "agrumeto"
  },
  {
    "id": "ang18",
    "code": "ANG18",
    "categoria": "Angoli extra ricevimento",
    "nome": "Alici del Cantabrico con crostini (100-150 invitati)",
    "titoloBase": "Alici del Cantabrico con crostini",
    "variante": "100-150 invitati",
    "descrizione": "Servizio Ufficiale TDA: Alici del Cantabrico con crostini (100-150 invitati) • Ripartizione: €100 Santo Stefano sul totale evento, resto Iovino",
    "prezzo_unitario": 500,
    "unita_misura": "corpo",
    "unitaLabel": "per evento",
    "splitLabel": "€100 Santo Stefano sul totale evento, resto Iovino",
    "splitKey": "angle",
    "immagine": "https://laterradegliaranci.it/wp-content/uploads/2024/07/sala-terradegliaranci.jpg",
    "costo_fornitore": 0,
    "fase_evento": "agrumeto"
  },
  {
    "id": "ang19",
    "code": "ANG19",
    "categoria": "Angoli extra ricevimento",
    "nome": "Alici del Cantabrico con crostini (&gt;150 invitati)",
    "titoloBase": "Alici del Cantabrico con crostini",
    "variante": "&gt;150 invitati",
    "descrizione": "Servizio Ufficiale TDA: Alici del Cantabrico con crostini (&gt;150 invitati) • Ripartizione: €100 Santo Stefano sul totale evento, resto Iovino",
    "prezzo_unitario": 600,
    "unita_misura": "corpo",
    "unitaLabel": "per evento",
    "splitLabel": "€100 Santo Stefano sul totale evento, resto Iovino",
    "splitKey": "angle",
    "immagine": "https://laterradegliaranci.it/wp-content/uploads/2024/07/sala-terradegliaranci.jpg",
    "costo_fornitore": 0,
    "fase_evento": "agrumeto"
  },
  {
    "id": "ang20",
    "code": "ANG20",
    "categoria": "Angoli extra ricevimento",
    "nome": "Montanare e calzoncini (70-100 adulti)",
    "titoloBase": "Montanare e calzoncini",
    "variante": "70-100 adulti",
    "descrizione": "Servizio Ufficiale TDA: Montanare e calzoncini (70-100 adulti) • Ripartizione: €100 Santo Stefano sul totale evento, resto Iovino",
    "prezzo_unitario": 300,
    "unita_misura": "corpo",
    "unitaLabel": "per evento",
    "splitLabel": "€100 Santo Stefano sul totale evento, resto Iovino",
    "splitKey": "angle",
    "immagine": "https://laterradegliaranci.it/wp-content/uploads/2025/01/c42f8af69b00ef4678797b3b0241ac2e.jpg",
    "costo_fornitore": 0,
    "fase_evento": "agrumeto"
  },
  {
    "id": "ang21",
    "code": "ANG21",
    "categoria": "Angoli extra ricevimento",
    "nome": "Montanare e calzoncini (100-150 invitati)",
    "titoloBase": "Montanare e calzoncini",
    "variante": "100-150 invitati",
    "descrizione": "Servizio Ufficiale TDA: Montanare e calzoncini (100-150 invitati) • Ripartizione: €100 Santo Stefano sul totale evento, resto Iovino",
    "prezzo_unitario": 400,
    "unita_misura": "corpo",
    "unitaLabel": "per evento",
    "splitLabel": "€100 Santo Stefano sul totale evento, resto Iovino",
    "splitKey": "angle",
    "immagine": "https://laterradegliaranci.it/wp-content/uploads/2025/01/c42f8af69b00ef4678797b3b0241ac2e.jpg",
    "costo_fornitore": 0,
    "fase_evento": "agrumeto"
  },
  {
    "id": "ang22",
    "code": "ANG22",
    "categoria": "Angoli extra ricevimento",
    "nome": "Tigelle (70-100 adulti)",
    "titoloBase": "Tigelle",
    "variante": "70-100 adulti",
    "descrizione": "Servizio Ufficiale TDA: Tigelle (70-100 adulti) • Ripartizione: €100 Santo Stefano sul totale evento, resto Iovino",
    "prezzo_unitario": 300,
    "unita_misura": "corpo",
    "unitaLabel": "per evento",
    "splitLabel": "€100 Santo Stefano sul totale evento, resto Iovino",
    "splitKey": "angle",
    "immagine": "https://laterradegliaranci.it/wp-content/uploads/2025/01/c42f8af69b00ef4678797b3b0241ac2e.jpg",
    "costo_fornitore": 0,
    "fase_evento": "agrumeto"
  },
  {
    "id": "ang23",
    "code": "ANG23",
    "categoria": "Angoli extra ricevimento",
    "nome": "Tigelle (100-150 invitati)",
    "titoloBase": "Tigelle",
    "variante": "100-150 invitati",
    "descrizione": "Servizio Ufficiale TDA: Tigelle (100-150 invitati) • Ripartizione: €100 Santo Stefano sul totale evento, resto Iovino",
    "prezzo_unitario": 400,
    "unita_misura": "corpo",
    "unitaLabel": "per evento",
    "splitLabel": "€100 Santo Stefano sul totale evento, resto Iovino",
    "splitKey": "angle",
    "immagine": "https://laterradegliaranci.it/wp-content/uploads/2025/01/c42f8af69b00ef4678797b3b0241ac2e.jpg",
    "costo_fornitore": 0,
    "fase_evento": "agrumeto"
  },
  {
    "id": "ang24",
    "code": "ANG24",
    "categoria": "Angoli extra ricevimento",
    "nome": "Pizza (70-100 adulti)",
    "titoloBase": "Pizza",
    "variante": "70-100 adulti",
    "descrizione": "Servizio Ufficiale TDA: Pizza (70-100 adulti) • Ripartizione: €100 Santo Stefano sul totale evento, resto Iovino",
    "prezzo_unitario": 1200,
    "unita_misura": "corpo",
    "unitaLabel": "per evento",
    "splitLabel": "€100 Santo Stefano sul totale evento, resto Iovino",
    "splitKey": "angle",
    "immagine": "https://laterradegliaranci.it/wp-content/uploads/2025/01/c42f8af69b00ef4678797b3b0241ac2e.jpg",
    "costo_fornitore": 0,
    "fase_evento": "agrumeto"
  },
  {
    "id": "ang25",
    "code": "ANG25",
    "categoria": "Angoli extra ricevimento",
    "nome": "Pizza (100-150 invitati)",
    "titoloBase": "Pizza",
    "variante": "100-150 invitati",
    "descrizione": "Servizio Ufficiale TDA: Pizza (100-150 invitati) • Ripartizione: €100 Santo Stefano sul totale evento, resto Iovino",
    "prezzo_unitario": 1500,
    "unita_misura": "corpo",
    "unitaLabel": "per evento",
    "splitLabel": "€100 Santo Stefano sul totale evento, resto Iovino",
    "splitKey": "angle",
    "immagine": "https://laterradegliaranci.it/wp-content/uploads/2025/01/c42f8af69b00ef4678797b3b0241ac2e.jpg",
    "costo_fornitore": 0,
    "fase_evento": "agrumeto"
  },
  {
    "id": "ang26",
    "code": "ANG26",
    "categoria": "Angoli extra ricevimento",
    "nome": "Sushi corner (Sushi, sashimi e fusion)",
    "titoloBase": "Sushi corner",
    "variante": "Sushi, sashimi e fusion",
    "descrizione": "Servizio Ufficiale TDA: Sushi corner (Sushi, sashimi e fusion) • Ripartizione: €100 Santo Stefano sul totale evento, resto Iovino",
    "prezzo_unitario": 15,
    "unita_misura": "pax",
    "unitaLabel": "per ospite",
    "splitLabel": "€100 Santo Stefano sul totale evento, resto Iovino",
    "splitKey": "angle",
    "immagine": "https://laterradegliaranci.it/wp-content/uploads/2024/07/sala-terradegliaranci.jpg",
    "costo_fornitore": 0,
    "fase_evento": "agrumeto"
  },
  {
    "id": "ang27",
    "code": "ANG27",
    "categoria": "Angoli extra ricevimento",
    "nome": "Brace in giardino terra e mare (70-100 adulti)",
    "titoloBase": "Brace in giardino terra e mare",
    "variante": "70-100 adulti",
    "descrizione": "Servizio Ufficiale TDA: Brace in giardino terra e mare (70-100 adulti) • Ripartizione: €100 Santo Stefano sul totale evento, resto Iovino",
    "prezzo_unitario": 1000,
    "unita_misura": "corpo",
    "unitaLabel": "per evento",
    "splitLabel": "€100 Santo Stefano sul totale evento, resto Iovino",
    "splitKey": "angle",
    "immagine": "https://laterradegliaranci.it/wp-content/uploads/2024/06/giardino-promesse.jpg",
    "costo_fornitore": 0,
    "fase_evento": "agrumeto"
  },
  {
    "id": "ang28",
    "code": "ANG28",
    "categoria": "Angoli extra ricevimento",
    "nome": "Brace in giardino terra e mare (100-150 invitati)",
    "titoloBase": "Brace in giardino terra e mare",
    "variante": "100-150 invitati",
    "descrizione": "Servizio Ufficiale TDA: Brace in giardino terra e mare (100-150 invitati) • Ripartizione: €100 Santo Stefano sul totale evento, resto Iovino",
    "prezzo_unitario": 1200,
    "unita_misura": "corpo",
    "unitaLabel": "per evento",
    "splitLabel": "€100 Santo Stefano sul totale evento, resto Iovino",
    "splitKey": "angle",
    "immagine": "https://laterradegliaranci.it/wp-content/uploads/2024/06/giardino-promesse.jpg",
    "costo_fornitore": 0,
    "fase_evento": "agrumeto"
  },
  {
    "id": "ang29",
    "code": "ANG29",
    "categoria": "Angoli extra ricevimento",
    "nome": "Brace in giardino terra e mare (&gt;150 invitati)",
    "titoloBase": "Brace in giardino terra e mare",
    "variante": "&gt;150 invitati",
    "descrizione": "Servizio Ufficiale TDA: Brace in giardino terra e mare (&gt;150 invitati) • Ripartizione: €100 Santo Stefano sul totale evento, resto Iovino",
    "prezzo_unitario": 1400,
    "unita_misura": "corpo",
    "unitaLabel": "per evento",
    "splitLabel": "€100 Santo Stefano sul totale evento, resto Iovino",
    "splitKey": "angle",
    "immagine": "https://laterradegliaranci.it/wp-content/uploads/2024/06/giardino-promesse.jpg",
    "costo_fornitore": 0,
    "fase_evento": "agrumeto"
  },
  {
    "id": "ang30",
    "code": "ANG30",
    "categoria": "Angoli extra ricevimento",
    "nome": "Brace in giardino terra (70-100 adulti)",
    "titoloBase": "Brace in giardino terra",
    "variante": "70-100 adulti",
    "descrizione": "Servizio Ufficiale TDA: Brace in giardino terra (70-100 adulti) • Ripartizione: €100 Santo Stefano sul totale evento, resto Iovino",
    "prezzo_unitario": 600,
    "unita_misura": "corpo",
    "unitaLabel": "per evento",
    "splitLabel": "€100 Santo Stefano sul totale evento, resto Iovino",
    "splitKey": "angle",
    "immagine": "https://laterradegliaranci.it/wp-content/uploads/2024/06/giardino-promesse.jpg",
    "costo_fornitore": 0,
    "fase_evento": "agrumeto"
  },
  {
    "id": "ang31",
    "code": "ANG31",
    "categoria": "Angoli extra ricevimento",
    "nome": "Brace in giardino terra (100-150 invitati)",
    "titoloBase": "Brace in giardino terra",
    "variante": "100-150 invitati",
    "descrizione": "Servizio Ufficiale TDA: Brace in giardino terra (100-150 invitati) • Ripartizione: €100 Santo Stefano sul totale evento, resto Iovino",
    "prezzo_unitario": 800,
    "unita_misura": "corpo",
    "unitaLabel": "per evento",
    "splitLabel": "€100 Santo Stefano sul totale evento, resto Iovino",
    "splitKey": "angle",
    "immagine": "https://laterradegliaranci.it/wp-content/uploads/2024/06/giardino-promesse.jpg",
    "costo_fornitore": 0,
    "fase_evento": "agrumeto"
  },
  {
    "id": "ang32",
    "code": "ANG32",
    "categoria": "Angoli extra ricevimento",
    "nome": "Brace in giardino terra (&gt;150 invitati)",
    "titoloBase": "Brace in giardino terra",
    "variante": "&gt;150 invitati",
    "descrizione": "Servizio Ufficiale TDA: Brace in giardino terra (&gt;150 invitati) • Ripartizione: €100 Santo Stefano sul totale evento, resto Iovino",
    "prezzo_unitario": 1000,
    "unita_misura": "corpo",
    "unitaLabel": "per evento",
    "splitLabel": "€100 Santo Stefano sul totale evento, resto Iovino",
    "splitKey": "angle",
    "immagine": "https://laterradegliaranci.it/wp-content/uploads/2024/06/giardino-promesse.jpg",
    "costo_fornitore": 0,
    "fase_evento": "agrumeto"
  },
  {
    "id": "ang33",
    "code": "ANG33",
    "categoria": "Angoli extra ricevimento",
    "nome": "Brace in giardino mare (70-100 adulti)",
    "titoloBase": "Brace in giardino mare",
    "variante": "70-100 adulti",
    "descrizione": "Servizio Ufficiale TDA: Brace in giardino mare (70-100 adulti) • Ripartizione: €100 Santo Stefano sul totale evento, resto Iovino",
    "prezzo_unitario": 800,
    "unita_misura": "corpo",
    "unitaLabel": "per evento",
    "splitLabel": "€100 Santo Stefano sul totale evento, resto Iovino",
    "splitKey": "angle",
    "immagine": "https://laterradegliaranci.it/wp-content/uploads/2024/06/giardino-promesse.jpg",
    "costo_fornitore": 0,
    "fase_evento": "agrumeto"
  },
  {
    "id": "ang34",
    "code": "ANG34",
    "categoria": "Angoli extra ricevimento",
    "nome": "Brace in giardino mare (100-150 invitati)",
    "titoloBase": "Brace in giardino mare",
    "variante": "100-150 invitati",
    "descrizione": "Servizio Ufficiale TDA: Brace in giardino mare (100-150 invitati) • Ripartizione: €100 Santo Stefano sul totale evento, resto Iovino",
    "prezzo_unitario": 1000,
    "unita_misura": "corpo",
    "unitaLabel": "per evento",
    "splitLabel": "€100 Santo Stefano sul totale evento, resto Iovino",
    "splitKey": "angle",
    "immagine": "https://laterradegliaranci.it/wp-content/uploads/2024/06/giardino-promesse.jpg",
    "costo_fornitore": 0,
    "fase_evento": "agrumeto"
  },
  {
    "id": "ang35",
    "code": "ANG35",
    "categoria": "Angoli extra ricevimento",
    "nome": "Brace in giardino mare (&gt;150 invitati)",
    "titoloBase": "Brace in giardino mare",
    "variante": "&gt;150 invitati",
    "descrizione": "Servizio Ufficiale TDA: Brace in giardino mare (&gt;150 invitati) • Ripartizione: €100 Santo Stefano sul totale evento, resto Iovino",
    "prezzo_unitario": 1200,
    "unita_misura": "corpo",
    "unitaLabel": "per evento",
    "splitLabel": "€100 Santo Stefano sul totale evento, resto Iovino",
    "splitKey": "angle",
    "immagine": "https://laterradegliaranci.it/wp-content/uploads/2024/06/giardino-promesse.jpg",
    "costo_fornitore": 0,
    "fase_evento": "agrumeto"
  },
  {
    "id": "ang36",
    "code": "ANG36",
    "categoria": "Angoli extra ricevimento",
    "nome": "Mini bun gourmet (70-100 adulti)",
    "titoloBase": "Mini bun gourmet",
    "variante": "70-100 adulti",
    "descrizione": "Servizio Ufficiale TDA: Mini bun gourmet (70-100 adulti) • Ripartizione: €100 Santo Stefano sul totale evento, resto Iovino",
    "prezzo_unitario": 800,
    "unita_misura": "corpo",
    "unitaLabel": "per evento",
    "splitLabel": "€100 Santo Stefano sul totale evento, resto Iovino",
    "splitKey": "angle",
    "immagine": "https://laterradegliaranci.it/wp-content/uploads/2025/01/c42f8af69b00ef4678797b3b0241ac2e.jpg",
    "costo_fornitore": 0,
    "fase_evento": "agrumeto"
  },
  {
    "id": "ang37",
    "code": "ANG37",
    "categoria": "Angoli extra ricevimento",
    "nome": "Mini bun gourmet (100-150 invitati)",
    "titoloBase": "Mini bun gourmet",
    "variante": "100-150 invitati",
    "descrizione": "Servizio Ufficiale TDA: Mini bun gourmet (100-150 invitati) • Ripartizione: €100 Santo Stefano sul totale evento, resto Iovino",
    "prezzo_unitario": 1000,
    "unita_misura": "corpo",
    "unitaLabel": "per evento",
    "splitLabel": "€100 Santo Stefano sul totale evento, resto Iovino",
    "splitKey": "angle",
    "immagine": "https://laterradegliaranci.it/wp-content/uploads/2025/01/c42f8af69b00ef4678797b3b0241ac2e.jpg",
    "costo_fornitore": 0,
    "fase_evento": "agrumeto"
  },
  {
    "id": "ang38",
    "code": "ANG38",
    "categoria": "Angoli extra ricevimento",
    "nome": "Mini bun gourmet (&gt;150 invitati)",
    "titoloBase": "Mini bun gourmet",
    "variante": "&gt;150 invitati",
    "descrizione": "Servizio Ufficiale TDA: Mini bun gourmet (&gt;150 invitati) • Ripartizione: €100 Santo Stefano sul totale evento, resto Iovino",
    "prezzo_unitario": 1200,
    "unita_misura": "corpo",
    "unitaLabel": "per evento",
    "splitLabel": "€100 Santo Stefano sul totale evento, resto Iovino",
    "splitKey": "angle",
    "immagine": "https://laterradegliaranci.it/wp-content/uploads/2025/01/c42f8af69b00ef4678797b3b0241ac2e.jpg",
    "costo_fornitore": 0,
    "fase_evento": "agrumeto"
  },
  {
    "id": "ang39",
    "code": "ANG39",
    "categoria": "Angoli extra ricevimento",
    "nome": "Barbeque Pork (70-100 adulti)",
    "titoloBase": "Barbeque Pork",
    "variante": "70-100 adulti",
    "descrizione": "Servizio Ufficiale TDA: Barbeque Pork (70-100 adulti) • Ripartizione: €100 Santo Stefano sul totale evento, resto Iovino",
    "prezzo_unitario": 600,
    "unita_misura": "corpo",
    "unitaLabel": "per evento",
    "splitLabel": "€100 Santo Stefano sul totale evento, resto Iovino",
    "splitKey": "angle",
    "immagine": "https://laterradegliaranci.it/wp-content/uploads/2024/07/sala-terradegliaranci.jpg",
    "costo_fornitore": 0,
    "fase_evento": "agrumeto"
  },
  {
    "id": "ang40",
    "code": "ANG40",
    "categoria": "Angoli extra ricevimento",
    "nome": "Barbeque Pork (100-150 invitati)",
    "titoloBase": "Barbeque Pork",
    "variante": "100-150 invitati",
    "descrizione": "Servizio Ufficiale TDA: Barbeque Pork (100-150 invitati) • Ripartizione: €100 Santo Stefano sul totale evento, resto Iovino",
    "prezzo_unitario": 700,
    "unita_misura": "corpo",
    "unitaLabel": "per evento",
    "splitLabel": "€100 Santo Stefano sul totale evento, resto Iovino",
    "splitKey": "angle",
    "immagine": "https://laterradegliaranci.it/wp-content/uploads/2024/07/sala-terradegliaranci.jpg",
    "costo_fornitore": 0,
    "fase_evento": "agrumeto"
  },
  {
    "id": "ang41",
    "code": "ANG41",
    "categoria": "Angoli extra ricevimento",
    "nome": "Barbeque Pork (&gt;150 invitati)",
    "titoloBase": "Barbeque Pork",
    "variante": "&gt;150 invitati",
    "descrizione": "Servizio Ufficiale TDA: Barbeque Pork (&gt;150 invitati) • Ripartizione: €100 Santo Stefano sul totale evento, resto Iovino",
    "prezzo_unitario": 800,
    "unita_misura": "corpo",
    "unitaLabel": "per evento",
    "splitLabel": "€100 Santo Stefano sul totale evento, resto Iovino",
    "splitKey": "angle",
    "immagine": "https://laterradegliaranci.it/wp-content/uploads/2024/07/sala-terradegliaranci.jpg",
    "costo_fornitore": 0,
    "fase_evento": "agrumeto"
  },
  {
    "id": "ang42",
    "code": "ANG42",
    "categoria": "Angoli extra ricevimento",
    "nome": "Degustazione vini e formaggi (70-100 adulti)",
    "titoloBase": "Degustazione vini e formaggi",
    "variante": "70-100 adulti",
    "descrizione": "Servizio Ufficiale TDA: Degustazione vini e formaggi (70-100 adulti) • Ripartizione: €100 Santo Stefano sul totale evento, resto Iovino",
    "prezzo_unitario": 700,
    "unita_misura": "corpo",
    "unitaLabel": "per evento",
    "splitLabel": "€100 Santo Stefano sul totale evento, resto Iovino",
    "splitKey": "angle",
    "immagine": "https://laterradegliaranci.it/wp-content/uploads/2024/07/sala-terradegliaranci.jpg",
    "costo_fornitore": 0,
    "fase_evento": "agrumeto"
  },
  {
    "id": "ang43",
    "code": "ANG43",
    "categoria": "Angoli extra ricevimento",
    "nome": "Degustazione vini e formaggi (100-150 invitati)",
    "titoloBase": "Degustazione vini e formaggi",
    "variante": "100-150 invitati",
    "descrizione": "Servizio Ufficiale TDA: Degustazione vini e formaggi (100-150 invitati) • Ripartizione: €100 Santo Stefano sul totale evento, resto Iovino",
    "prezzo_unitario": 800,
    "unita_misura": "corpo",
    "unitaLabel": "per evento",
    "splitLabel": "€100 Santo Stefano sul totale evento, resto Iovino",
    "splitKey": "angle",
    "immagine": "https://laterradegliaranci.it/wp-content/uploads/2024/07/sala-terradegliaranci.jpg",
    "costo_fornitore": 0,
    "fase_evento": "agrumeto"
  },
  {
    "id": "ang44",
    "code": "ANG44",
    "categoria": "Angoli extra ricevimento",
    "nome": "Degustazione vini e formaggi (&gt;150 invitati)",
    "titoloBase": "Degustazione vini e formaggi",
    "variante": "&gt;150 invitati",
    "descrizione": "Servizio Ufficiale TDA: Degustazione vini e formaggi (&gt;150 invitati) • Ripartizione: €100 Santo Stefano sul totale evento, resto Iovino",
    "prezzo_unitario": 900,
    "unita_misura": "corpo",
    "unitaLabel": "per evento",
    "splitLabel": "€100 Santo Stefano sul totale evento, resto Iovino",
    "splitKey": "angle",
    "immagine": "https://laterradegliaranci.it/wp-content/uploads/2024/07/sala-terradegliaranci.jpg",
    "costo_fornitore": 0,
    "fase_evento": "agrumeto"
  },
  {
    "id": "ang45",
    "code": "ANG45",
    "categoria": "Angoli extra ricevimento",
    "nome": "Birra artigianale alla spina (70-100 adulti)",
    "titoloBase": "Birra artigianale alla spina",
    "variante": "70-100 adulti",
    "descrizione": "Servizio Ufficiale TDA: Birra artigianale alla spina (70-100 adulti) • Ripartizione: €100 Santo Stefano sul totale evento, resto Iovino",
    "prezzo_unitario": 700,
    "unita_misura": "corpo",
    "unitaLabel": "per evento",
    "splitLabel": "€100 Santo Stefano sul totale evento, resto Iovino",
    "splitKey": "angle",
    "immagine": "https://laterradegliaranci.it/wp-content/uploads/2024/07/sala-terradegliaranci.jpg",
    "costo_fornitore": 0,
    "fase_evento": "agrumeto"
  },
  {
    "id": "ang46",
    "code": "ANG46",
    "categoria": "Angoli extra ricevimento",
    "nome": "Birra artigianale alla spina (100-150 invitati)",
    "titoloBase": "Birra artigianale alla spina",
    "variante": "100-150 invitati",
    "descrizione": "Servizio Ufficiale TDA: Birra artigianale alla spina (100-150 invitati) • Ripartizione: €100 Santo Stefano sul totale evento, resto Iovino",
    "prezzo_unitario": 800,
    "unita_misura": "corpo",
    "unitaLabel": "per evento",
    "splitLabel": "€100 Santo Stefano sul totale evento, resto Iovino",
    "splitKey": "angle",
    "immagine": "https://laterradegliaranci.it/wp-content/uploads/2024/07/sala-terradegliaranci.jpg",
    "costo_fornitore": 0,
    "fase_evento": "agrumeto"
  },
  {
    "id": "ang47",
    "code": "ANG47",
    "categoria": "Angoli extra ricevimento",
    "nome": "Birra artigianale alla spina (&gt;150 invitati)",
    "titoloBase": "Birra artigianale alla spina",
    "variante": "&gt;150 invitati",
    "descrizione": "Servizio Ufficiale TDA: Birra artigianale alla spina (&gt;150 invitati) • Ripartizione: €100 Santo Stefano sul totale evento, resto Iovino",
    "prezzo_unitario": 900,
    "unita_misura": "corpo",
    "unitaLabel": "per evento",
    "splitLabel": "€100 Santo Stefano sul totale evento, resto Iovino",
    "splitKey": "angle",
    "immagine": "https://laterradegliaranci.it/wp-content/uploads/2024/07/sala-terradegliaranci.jpg",
    "costo_fornitore": 0,
    "fase_evento": "agrumeto"
  },
  {
    "id": "ang48",
    "code": "ANG48",
    "categoria": "Angoli extra ricevimento",
    "nome": "Birra artigianale imbottigliata (70-100 adulti)",
    "titoloBase": "Birra artigianale imbottigliata",
    "variante": "70-100 adulti",
    "descrizione": "Servizio Ufficiale TDA: Birra artigianale imbottigliata (70-100 adulti) • Ripartizione: €100 Santo Stefano sul totale evento, resto Iovino",
    "prezzo_unitario": 400,
    "unita_misura": "corpo",
    "unitaLabel": "per evento",
    "splitLabel": "€100 Santo Stefano sul totale evento, resto Iovino",
    "splitKey": "angle",
    "immagine": "https://laterradegliaranci.it/wp-content/uploads/2024/07/sala-terradegliaranci.jpg",
    "costo_fornitore": 0,
    "fase_evento": "agrumeto"
  },
  {
    "id": "ang49",
    "code": "ANG49",
    "categoria": "Angoli extra ricevimento",
    "nome": "Birra artigianale imbottigliata (100-150 invitati)",
    "titoloBase": "Birra artigianale imbottigliata",
    "variante": "100-150 invitati",
    "descrizione": "Servizio Ufficiale TDA: Birra artigianale imbottigliata (100-150 invitati) • Ripartizione: €100 Santo Stefano sul totale evento, resto Iovino",
    "prezzo_unitario": 600,
    "unita_misura": "corpo",
    "unitaLabel": "per evento",
    "splitLabel": "€100 Santo Stefano sul totale evento, resto Iovino",
    "splitKey": "angle",
    "immagine": "https://laterradegliaranci.it/wp-content/uploads/2024/07/sala-terradegliaranci.jpg",
    "costo_fornitore": 0,
    "fase_evento": "agrumeto"
  },
  {
    "id": "ang50",
    "code": "ANG50",
    "categoria": "Angoli extra ricevimento",
    "nome": "Birra artigianale imbottigliata (&gt;150 invitati)",
    "titoloBase": "Birra artigianale imbottigliata",
    "variante": "&gt;150 invitati",
    "descrizione": "Servizio Ufficiale TDA: Birra artigianale imbottigliata (&gt;150 invitati) • Ripartizione: €100 Santo Stefano sul totale evento, resto Iovino",
    "prezzo_unitario": 800,
    "unita_misura": "corpo",
    "unitaLabel": "per evento",
    "splitLabel": "€100 Santo Stefano sul totale evento, resto Iovino",
    "splitKey": "angle",
    "immagine": "https://laterradegliaranci.it/wp-content/uploads/2024/07/sala-terradegliaranci.jpg",
    "costo_fornitore": 0,
    "fase_evento": "agrumeto"
  },
  {
    "id": "ang51",
    "code": "ANG51",
    "categoria": "Angoli extra ricevimento",
    "nome": "Secondo di pescato (Extra menu)",
    "titoloBase": "Secondo di pescato",
    "variante": "Extra menu",
    "descrizione": "Servizio Ufficiale TDA: Secondo di pescato (Extra menu) • Ripartizione: €100 Santo Stefano sul totale evento, resto Iovino",
    "prezzo_unitario": 7,
    "unita_misura": "pax",
    "unitaLabel": "per persona",
    "splitLabel": "€100 Santo Stefano sul totale evento, resto Iovino",
    "splitKey": "angle",
    "immagine": "https://laterradegliaranci.it/wp-content/uploads/2024/07/sala-terradegliaranci.jpg",
    "costo_fornitore": 0,
    "fase_evento": "agrumeto"
  },
  {
    "id": "ang52",
    "code": "ANG52",
    "categoria": "Angoli extra ricevimento",
    "nome": "Primo all'astice (Extra menu)",
    "titoloBase": "Primo all'astice",
    "variante": "Extra menu",
    "descrizione": "Servizio Ufficiale TDA: Primo all'astice (Extra menu) • Ripartizione: €100 Santo Stefano sul totale evento, resto Iovino",
    "prezzo_unitario": 5,
    "unita_misura": "pax",
    "unitaLabel": "per persona",
    "splitLabel": "€100 Santo Stefano sul totale evento, resto Iovino",
    "splitKey": "angle",
    "immagine": "https://laterradegliaranci.it/wp-content/uploads/2024/07/sala-terradegliaranci.jpg",
    "costo_fornitore": 0,
    "fase_evento": "agrumeto"
  },
  {
    "id": "ang53",
    "code": "ANG53",
    "categoria": "Angoli extra ricevimento",
    "nome": "Confettata (70-120 invitati)",
    "titoloBase": "Confettata",
    "variante": "70-120 invitati",
    "descrizione": "Servizio Ufficiale TDA: Confettata (70-120 invitati) • Ripartizione: €100 Santo Stefano sul totale evento, resto Iovino",
    "prezzo_unitario": 400,
    "unita_misura": "corpo",
    "unitaLabel": "per evento",
    "splitLabel": "€100 Santo Stefano sul totale evento, resto Iovino",
    "splitKey": "angle",
    "immagine": "https://laterradegliaranci.it/wp-content/uploads/2024/07/sala-terradegliaranci.jpg",
    "costo_fornitore": 0,
    "fase_evento": "torta"
  },
  {
    "id": "ang54",
    "code": "ANG54",
    "categoria": "Angoli extra ricevimento",
    "nome": "Confettata (120-150 invitati)",
    "titoloBase": "Confettata",
    "variante": "120-150 invitati",
    "descrizione": "Servizio Ufficiale TDA: Confettata (120-150 invitati) • Ripartizione: €100 Santo Stefano sul totale evento, resto Iovino",
    "prezzo_unitario": 500,
    "unita_misura": "corpo",
    "unitaLabel": "per evento",
    "splitLabel": "€100 Santo Stefano sul totale evento, resto Iovino",
    "splitKey": "angle",
    "immagine": "https://laterradegliaranci.it/wp-content/uploads/2024/07/sala-terradegliaranci.jpg",
    "costo_fornitore": 0,
    "fase_evento": "torta"
  },
  {
    "id": "ang55",
    "code": "ANG55",
    "categoria": "Angoli extra ricevimento",
    "nome": "Confettata (&gt;150 invitati)",
    "titoloBase": "Confettata",
    "variante": "&gt;150 invitati",
    "descrizione": "Servizio Ufficiale TDA: Confettata (&gt;150 invitati) • Ripartizione: €100 Santo Stefano sul totale evento, resto Iovino",
    "prezzo_unitario": 600,
    "unita_misura": "corpo",
    "unitaLabel": "per evento",
    "splitLabel": "€100 Santo Stefano sul totale evento, resto Iovino",
    "splitKey": "angle",
    "immagine": "https://laterradegliaranci.it/wp-content/uploads/2024/07/sala-terradegliaranci.jpg",
    "costo_fornitore": 0,
    "fase_evento": "torta"
  },
  {
    "id": "ang56",
    "code": "ANG56",
    "categoria": "Angoli extra ricevimento",
    "nome": "Angolo cubano (70-100 adulti)",
    "titoloBase": "Angolo cubano",
    "variante": "70-100 adulti",
    "descrizione": "Servizio Ufficiale TDA: Angolo cubano (70-100 adulti) • Ripartizione: €100 Santo Stefano sul totale evento, resto Iovino",
    "prezzo_unitario": 700,
    "unita_misura": "corpo",
    "unitaLabel": "per evento",
    "splitLabel": "€100 Santo Stefano sul totale evento, resto Iovino",
    "splitKey": "angle",
    "immagine": "https://laterradegliaranci.it/wp-content/uploads/2024/07/sala-terradegliaranci.jpg",
    "costo_fornitore": 0,
    "fase_evento": "agrumeto"
  },
  {
    "id": "ang57",
    "code": "ANG57",
    "categoria": "Angoli extra ricevimento",
    "nome": "Angolo cubano (100-150 invitati)",
    "titoloBase": "Angolo cubano",
    "variante": "100-150 invitati",
    "descrizione": "Servizio Ufficiale TDA: Angolo cubano (100-150 invitati) • Ripartizione: €100 Santo Stefano sul totale evento, resto Iovino",
    "prezzo_unitario": 850,
    "unita_misura": "corpo",
    "unitaLabel": "per evento",
    "splitLabel": "€100 Santo Stefano sul totale evento, resto Iovino",
    "splitKey": "angle",
    "immagine": "https://laterradegliaranci.it/wp-content/uploads/2024/07/sala-terradegliaranci.jpg",
    "costo_fornitore": 0,
    "fase_evento": "agrumeto"
  },
  {
    "id": "ang58",
    "code": "ANG58",
    "categoria": "Angoli extra ricevimento",
    "nome": "Angolo cubano (&gt;150 invitati)",
    "titoloBase": "Angolo cubano",
    "variante": "&gt;150 invitati",
    "descrizione": "Servizio Ufficiale TDA: Angolo cubano (&gt;150 invitati) • Ripartizione: €100 Santo Stefano sul totale evento, resto Iovino",
    "prezzo_unitario": 1000,
    "unita_misura": "corpo",
    "unitaLabel": "per evento",
    "splitLabel": "€100 Santo Stefano sul totale evento, resto Iovino",
    "splitKey": "angle",
    "immagine": "https://laterradegliaranci.it/wp-content/uploads/2024/07/sala-terradegliaranci.jpg",
    "costo_fornitore": 0,
    "fase_evento": "agrumeto"
  },
  {
    "id": "ang59",
    "code": "ANG59",
    "categoria": "Angoli extra ricevimento",
    "nome": "Angolo liquori (Fino a 100 ospiti)",
    "titoloBase": "Angolo liquori",
    "variante": "Fino a 100 ospiti",
    "descrizione": "Servizio Ufficiale TDA: Angolo liquori (Fino a 100 ospiti) • Ripartizione: €100 Santo Stefano sul totale evento, resto Iovino",
    "prezzo_unitario": 600,
    "unita_misura": "corpo",
    "unitaLabel": "per evento",
    "splitLabel": "€100 Santo Stefano sul totale evento, resto Iovino",
    "splitKey": "angle",
    "immagine": "https://laterradegliaranci.it/wp-content/uploads/2024/07/sala-terradegliaranci.jpg",
    "costo_fornitore": 0,
    "fase_evento": "agrumeto"
  },
  {
    "id": "ang60",
    "code": "ANG60",
    "categoria": "Angoli extra ricevimento",
    "nome": "Angolo liquori (100-150 ospiti)",
    "titoloBase": "Angolo liquori",
    "variante": "100-150 ospiti",
    "descrizione": "Servizio Ufficiale TDA: Angolo liquori (100-150 ospiti) • Ripartizione: €100 Santo Stefano sul totale evento, resto Iovino",
    "prezzo_unitario": 900,
    "unita_misura": "corpo",
    "unitaLabel": "per evento",
    "splitLabel": "€100 Santo Stefano sul totale evento, resto Iovino",
    "splitKey": "angle",
    "immagine": "https://laterradegliaranci.it/wp-content/uploads/2024/07/sala-terradegliaranci.jpg",
    "costo_fornitore": 0,
    "fase_evento": "agrumeto"
  },
  {
    "id": "ang61",
    "code": "ANG61",
    "categoria": "Angoli extra ricevimento",
    "nome": "Angolo gelati (70-120 invitati)",
    "titoloBase": "Angolo gelati",
    "variante": "70-120 invitati",
    "descrizione": "Servizio Ufficiale TDA: Angolo gelati (70-120 invitati) • Ripartizione: €100 Santo Stefano sul totale evento, resto Iovino",
    "prezzo_unitario": 600,
    "unita_misura": "corpo",
    "unitaLabel": "per evento",
    "splitLabel": "€100 Santo Stefano sul totale evento, resto Iovino",
    "splitKey": "angle",
    "immagine": "https://laterradegliaranci.it/wp-content/uploads/2024/07/sala-terradegliaranci.jpg",
    "costo_fornitore": 0,
    "fase_evento": "torta"
  },
  {
    "id": "ang62",
    "code": "ANG62",
    "categoria": "Angoli extra ricevimento",
    "nome": "Angolo gelati (120-150 invitati)",
    "titoloBase": "Angolo gelati",
    "variante": "120-150 invitati",
    "descrizione": "Servizio Ufficiale TDA: Angolo gelati (120-150 invitati) • Ripartizione: €100 Santo Stefano sul totale evento, resto Iovino",
    "prezzo_unitario": 700,
    "unita_misura": "corpo",
    "unitaLabel": "per evento",
    "splitLabel": "€100 Santo Stefano sul totale evento, resto Iovino",
    "splitKey": "angle",
    "immagine": "https://laterradegliaranci.it/wp-content/uploads/2024/07/sala-terradegliaranci.jpg",
    "costo_fornitore": 0,
    "fase_evento": "torta"
  },
  {
    "id": "ang63",
    "code": "ANG63",
    "categoria": "Angoli extra ricevimento",
    "nome": "Fontana di cioccolato (70-100 adulti)",
    "titoloBase": "Fontana di cioccolato",
    "variante": "70-100 adulti",
    "descrizione": "Servizio Ufficiale TDA: Fontana di cioccolato (70-100 adulti) • Ripartizione: €100 Santo Stefano sul totale evento, resto Iovino",
    "prezzo_unitario": 400,
    "unita_misura": "corpo",
    "unitaLabel": "per evento",
    "splitLabel": "€100 Santo Stefano sul totale evento, resto Iovino",
    "splitKey": "angle",
    "immagine": "https://laterradegliaranci.it/wp-content/uploads/2024/07/sala-terradegliaranci.jpg",
    "costo_fornitore": 0,
    "fase_evento": "torta"
  },
  {
    "id": "ang64",
    "code": "ANG64",
    "categoria": "Angoli extra ricevimento",
    "nome": "Fontana di cioccolato (100-150 invitati)",
    "titoloBase": "Fontana di cioccolato",
    "variante": "100-150 invitati",
    "descrizione": "Servizio Ufficiale TDA: Fontana di cioccolato (100-150 invitati) • Ripartizione: €100 Santo Stefano sul totale evento, resto Iovino",
    "prezzo_unitario": 500,
    "unita_misura": "corpo",
    "unitaLabel": "per evento",
    "splitLabel": "€100 Santo Stefano sul totale evento, resto Iovino",
    "splitKey": "angle",
    "immagine": "https://laterradegliaranci.it/wp-content/uploads/2024/07/sala-terradegliaranci.jpg",
    "costo_fornitore": 0,
    "fase_evento": "torta"
  },
  {
    "id": "ang65",
    "code": "ANG65",
    "categoria": "Angoli extra ricevimento",
    "nome": "Graffette fritte show cooking (70-100 adulti)",
    "titoloBase": "Graffette fritte show cooking",
    "variante": "70-100 adulti",
    "descrizione": "Servizio Ufficiale TDA: Graffette fritte show cooking (70-100 adulti) • Ripartizione: €100 Santo Stefano sul totale evento, resto Iovino",
    "prezzo_unitario": 250,
    "unita_misura": "corpo",
    "unitaLabel": "per evento",
    "splitLabel": "€100 Santo Stefano sul totale evento, resto Iovino",
    "splitKey": "angle",
    "immagine": "https://laterradegliaranci.it/wp-content/uploads/2024/07/sala-terradegliaranci.jpg",
    "costo_fornitore": 0,
    "fase_evento": "torta"
  },
  {
    "id": "ang66",
    "code": "ANG66",
    "categoria": "Angoli extra ricevimento",
    "nome": "Graffette fritte show cooking (100-150 invitati)",
    "titoloBase": "Graffette fritte show cooking",
    "variante": "100-150 invitati",
    "descrizione": "Servizio Ufficiale TDA: Graffette fritte show cooking (100-150 invitati) • Ripartizione: €100 Santo Stefano sul totale evento, resto Iovino",
    "prezzo_unitario": 350,
    "unita_misura": "corpo",
    "unitaLabel": "per evento",
    "splitLabel": "€100 Santo Stefano sul totale evento, resto Iovino",
    "splitKey": "angle",
    "immagine": "https://laterradegliaranci.it/wp-content/uploads/2024/07/sala-terradegliaranci.jpg",
    "costo_fornitore": 0,
    "fase_evento": "torta"
  },
  {
    "id": "ult01",
    "code": "ULT01",
    "categoria": "Servizi ulteriori",
    "nome": "Servizio ulteriore non previsto 1 (Da descrivere)",
    "titoloBase": "Servizio ulteriore non previsto 1",
    "variante": "Da descrivere",
    "descrizione": "Servizio Ufficiale TDA: Servizio ulteriore non previsto 1 (Da descrivere) • Ripartizione: Da scegliere tramite codice riparto",
    "prezzo_unitario": 0,
    "unita_misura": "corpo",
    "unitaLabel": "da quotare",
    "splitLabel": "Da scegliere tramite codice riparto",
    "splitKey": "40_60",
    "immagine": "https://laterradegliaranci.it/wp-content/uploads/2024/07/sala-terradegliaranci.jpg",
    "costo_fornitore": 0,
    "fase_evento": "generale"
  },
  {
    "id": "ult02",
    "code": "ULT02",
    "categoria": "Servizi ulteriori",
    "nome": "Servizio ulteriore non previsto 2 (Da descrivere)",
    "titoloBase": "Servizio ulteriore non previsto 2",
    "variante": "Da descrivere",
    "descrizione": "Servizio Ufficiale TDA: Servizio ulteriore non previsto 2 (Da descrivere) • Ripartizione: Da scegliere tramite codice riparto",
    "prezzo_unitario": 0,
    "unita_misura": "corpo",
    "unitaLabel": "da quotare",
    "splitLabel": "Da scegliere tramite codice riparto",
    "splitKey": "40_60",
    "immagine": "https://laterradegliaranci.it/wp-content/uploads/2024/07/sala-terradegliaranci.jpg",
    "costo_fornitore": 0,
    "fase_evento": "generale"
  },
  {
    "id": "ult03",
    "code": "ULT03",
    "categoria": "Servizi ulteriori",
    "nome": "Servizio ulteriore non previsto 3 (Da descrivere)",
    "titoloBase": "Servizio ulteriore non previsto 3",
    "variante": "Da descrivere",
    "descrizione": "Servizio Ufficiale TDA: Servizio ulteriore non previsto 3 (Da descrivere) • Ripartizione: Da scegliere tramite codice riparto",
    "prezzo_unitario": 0,
    "unita_misura": "corpo",
    "unitaLabel": "da quotare",
    "splitLabel": "Da scegliere tramite codice riparto",
    "splitKey": "40_60",
    "immagine": "https://laterradegliaranci.it/wp-content/uploads/2024/07/sala-terradegliaranci.jpg",
    "costo_fornitore": 0,
    "fase_evento": "generale"
  },
  {
    "id": "ult04",
    "code": "ULT04",
    "categoria": "Servizi ulteriori",
    "nome": "Servizio ulteriore non previsto 4 (Da descrivere)",
    "titoloBase": "Servizio ulteriore non previsto 4",
    "variante": "Da descrivere",
    "descrizione": "Servizio Ufficiale TDA: Servizio ulteriore non previsto 4 (Da descrivere) • Ripartizione: Da scegliere tramite codice riparto",
    "prezzo_unitario": 0,
    "unita_misura": "corpo",
    "unitaLabel": "da quotare",
    "splitLabel": "Da scegliere tramite codice riparto",
    "splitKey": "40_60",
    "immagine": "https://laterradegliaranci.it/wp-content/uploads/2024/07/sala-terradegliaranci.jpg",
    "costo_fornitore": 0,
    "fase_evento": "generale"
  },
  {
    "id": "ult05",
    "code": "ULT05",
    "categoria": "Servizi ulteriori",
    "nome": "Servizio ulteriore non previsto 5 (Da descrivere)",
    "titoloBase": "Servizio ulteriore non previsto 5",
    "variante": "Da descrivere",
    "descrizione": "Servizio Ufficiale TDA: Servizio ulteriore non previsto 5 (Da descrivere) • Ripartizione: Da scegliere tramite codice riparto",
    "prezzo_unitario": 0,
    "unita_misura": "corpo",
    "unitaLabel": "da quotare",
    "splitLabel": "Da scegliere tramite codice riparto",
    "splitKey": "40_60",
    "immagine": "https://laterradegliaranci.it/wp-content/uploads/2024/07/sala-terradegliaranci.jpg",
    "costo_fornitore": 0,
    "fase_evento": "generale"
  },
  {
    "id": "ult06",
    "code": "ULT06",
    "categoria": "Servizi ulteriori",
    "nome": "Servizio ulteriore non previsto 6 (Da descrivere)",
    "titoloBase": "Servizio ulteriore non previsto 6",
    "variante": "Da descrivere",
    "descrizione": "Servizio Ufficiale TDA: Servizio ulteriore non previsto 6 (Da descrivere) • Ripartizione: Da scegliere tramite codice riparto",
    "prezzo_unitario": 0,
    "unita_misura": "corpo",
    "unitaLabel": "da quotare",
    "splitLabel": "Da scegliere tramite codice riparto",
    "splitKey": "40_60",
    "immagine": "https://laterradegliaranci.it/wp-content/uploads/2024/07/sala-terradegliaranci.jpg",
    "costo_fornitore": 0,
    "fase_evento": "generale"
  },
  {
    "id": "ult07",
    "code": "ULT07",
    "categoria": "Servizi ulteriori",
    "nome": "Servizio ulteriore non previsto 7 (Da descrivere)",
    "titoloBase": "Servizio ulteriore non previsto 7",
    "variante": "Da descrivere",
    "descrizione": "Servizio Ufficiale TDA: Servizio ulteriore non previsto 7 (Da descrivere) • Ripartizione: Da scegliere tramite codice riparto",
    "prezzo_unitario": 0,
    "unita_misura": "corpo",
    "unitaLabel": "da quotare",
    "splitLabel": "Da scegliere tramite codice riparto",
    "splitKey": "40_60",
    "immagine": "https://laterradegliaranci.it/wp-content/uploads/2024/07/sala-terradegliaranci.jpg",
    "costo_fornitore": 0,
    "fase_evento": "generale"
  },
  {
    "id": "ult08",
    "code": "ULT08",
    "categoria": "Servizi ulteriori",
    "nome": "Servizio ulteriore non previsto 8 (Da descrivere)",
    "titoloBase": "Servizio ulteriore non previsto 8",
    "variante": "Da descrivere",
    "descrizione": "Servizio Ufficiale TDA: Servizio ulteriore non previsto 8 (Da descrivere) • Ripartizione: Da scegliere tramite codice riparto",
    "prezzo_unitario": 0,
    "unita_misura": "corpo",
    "unitaLabel": "da quotare",
    "splitLabel": "Da scegliere tramite codice riparto",
    "splitKey": "40_60",
    "immagine": "https://laterradegliaranci.it/wp-content/uploads/2024/07/sala-terradegliaranci.jpg",
    "costo_fornitore": 0,
    "fase_evento": "generale"
  },
  {
    "id": "ult09",
    "code": "ULT09",
    "categoria": "Servizi ulteriori",
    "nome": "Servizio ulteriore non previsto 9 (Da descrivere)",
    "titoloBase": "Servizio ulteriore non previsto 9",
    "variante": "Da descrivere",
    "descrizione": "Servizio Ufficiale TDA: Servizio ulteriore non previsto 9 (Da descrivere) • Ripartizione: Da scegliere tramite codice riparto",
    "prezzo_unitario": 0,
    "unita_misura": "corpo",
    "unitaLabel": "da quotare",
    "splitLabel": "Da scegliere tramite codice riparto",
    "splitKey": "40_60",
    "immagine": "https://laterradegliaranci.it/wp-content/uploads/2024/07/sala-terradegliaranci.jpg",
    "costo_fornitore": 0,
    "fase_evento": "generale"
  },
  {
    "id": "ult10",
    "code": "ULT10",
    "categoria": "Servizi ulteriori",
    "nome": "Servizio ulteriore non previsto 10 (Da descrivere)",
    "titoloBase": "Servizio ulteriore non previsto 10",
    "variante": "Da descrivere",
    "descrizione": "Servizio Ufficiale TDA: Servizio ulteriore non previsto 10 (Da descrivere) • Ripartizione: Da scegliere tramite codice riparto",
    "prezzo_unitario": 0,
    "unita_misura": "corpo",
    "unitaLabel": "da quotare",
    "splitLabel": "Da scegliere tramite codice riparto",
    "splitKey": "40_60",
    "immagine": "https://laterradegliaranci.it/wp-content/uploads/2024/07/sala-terradegliaranci.jpg",
    "costo_fornitore": 0,
    "fase_evento": "generale"
  }
];
